insert into from_bodies (from_id, body_name) values (135,"ITU-T SG 15, Q.14/15");
insert into from_bodies (from_id, body_name) values (136,"ATM Forum AIC WG");
insert into from_bodies (from_id, body_name) values (137,"MPLS and FR Alliance");
insert into from_bodies (from_id, body_name) values (138,"ISO/IEC JTC 1 SC 29/WG 11");
insert into from_bodies (from_id, body_name) values (139,"ITU-T SG 15 WP 1");
insert into from_bodies (from_id, body_name) values (140,"IETF Transport Area");
insert into from_bodies (from_id, body_name) values (141,"T1S1");
insert into from_bodies (from_id, body_name) values (142,"ITU-T Q.5/13");
insert into from_bodies (from_id, body_name) values (143,"IETF DISMAN WG");
insert into from_bodies (from_id, body_name) values (144,"ITU-T SG 15 Q14/15");
insert into from_bodies (from_id, body_name) values (145,"IETF ENUM WG");
insert into from_bodies (from_id, body_name) values (146,"IETF Mobile IP WG");
insert into from_bodies (from_id, body_name) values (147,"ITUT-T SG 16");
insert into from_bodies (from_id, body_name) values (148,"T1M1");
insert into from_bodies (from_id, body_name) values (149,"Sigtran WG");
insert into from_bodies (from_id, body_name) values (150,"T1X1 cc: ITU-T Q. 14/15 (for info)");
insert into from_bodies (from_id, body_name) values (151,"MPLS Forum");
insert into from_bodies (from_id, body_name) values (152,"IETF SUB-IP Area");
insert into from_bodies (from_id, body_name) values (153,"AVT WG");
insert into from_bodies (from_id, body_name) values (154,"SIP, SIPPING, SIMPLE WGs");
insert into from_bodies (from_id, body_name) values (155,"WIG");
insert into from_bodies (from_id, body_name) values (156,"SC 29/WG 11");
insert into from_bodies (from_id, body_name) values (157,"SC 29/WG 1");
insert into from_bodies (from_id, body_name) values (158,"ISO/IEC JTC SC 29/WG11");
insert into from_bodies (from_id, body_name) values (159,"IETF Sub-IP Area");
insert into from_bodies (from_id, body_name) values (160,"ISO/IEC JTC SC 29/WG1");
insert into from_bodies (from_id, body_name) values (161,"ITU-Q.14/15");
insert into from_bodies (from_id, body_name) values (162,"ITU-T SG 15, Q.11");
insert into from_bodies (from_id, body_name) values (163,"ITU-SC29");
insert into from_bodies (from_id, body_name) values (164,"SC29 4559");
insert into from_bodies (from_id, body_name) values (165,"SC29 4561");
insert into from_bodies (from_id, body_name) values (166,"Sigtran");
insert into from_bodies (from_id, body_name) values (167,"ITU-T SG 7");
insert into from_bodies (from_id, body_name) values (168,"ITU-SG 15");
insert into from_bodies (from_id, body_name) values (169,"ISO/IEC JTC1/SC29/WG11");
insert into from_bodies (from_id, body_name) values (170,"ITU-SG 7");
insert into from_bodies (from_id, body_name) values (171,"ITU-SG 8");
insert into from_bodies (from_id, body_name) values (172,"ISO/IEC JTC1/SC6");
insert into uploads (file_id,file_title,file_extension,detail_id) values (800,' Liaison Statement To IETF CCAMP WG on draft-ietf-ccamp-gmpls-ason-reqts',".html",700);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (700,"2004-02-01",135,"IETF CCAMP WG Chairs",1,NULL,"IETF CCAMP WG Chairs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (801,' Response to IETF CCAMP WG regarding Comments on G.7713.2',".html",701);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (701,"2004-02-01",73,"IETF CCAMP",1,NULL,"IETF CCAMP");
insert into uploads (file_id,file_title,file_extension,detail_id) values (802,' Response To IETF CCAMP WG on ASON Routing Requirements',".html",702);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (702,"2004-02-01",135,"IETF CCAMP WG Chairs",1,NULL,"IETF CCAMP WG Chairs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (803,' Information on L1VPN related work in SG 13',".pdf",703);
insert into uploads (file_id,file_title,file_extension,detail_id) values (804,' Questionnaire in the area of Layer 1 VPN series',".pdf",703);
insert into uploads (file_id,file_title,file_extension,detail_id) values (805,' Document summerizing Layer ! VPN work in SG 13 up to now',".pdf",703);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (703,"2004-02-01",113,"IETF Routing Area (CCAMP WG) and Internet Area (L2VPN WG and L3VPN WG)",1,NULL,"IETF Routing Area (CCAMP WG) and Internet Area (L2VPN WG and L3VPN WG)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (806,' L2VPN over MPLS solution space',".pdf",704);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (704,"2004-02-01",113,"IETF Internet Area (L2VPN WG)",1,NULL,"IETF Internet Area (L2VPN WG)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (807,' TDM-MPLS network interworking',".pdf",705);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (705,"2004-02-01",113,"IETF PWE3 WG",1,NULL,"IETF PWE3 WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (808,' Reply to the Liaison on Structured Probable Cause',".pdf",706);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (706,"2004-02-01",113,"IETF DISMAN WG",1,NULL,"IETF DISMAN WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (809,' Liaison Statement on NGN Studies',".pdf",707);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (707,"2004-02-01",113,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (810,' Liaison Statement to ITU-T SGs, ITU-R WGs, IETF on the ITU-T IP Project',".pdf",708);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (708,"2004-02-01",113,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (811,' Laiason from ATM Forum to PWE3 Working Group',".txt",709);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (709,"2004-02-01",136,"PWE3 Working Greoup Chairs",1,NULL,"PWE3 Working Greoup Chairs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (812,' MINUTES: IETF/W3C coordination call',".txt",710);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (710,"2004-02-01",7,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (813,' Liaison from MPLS and Frame Relay Alliance to PWE3 WG',".txt",711);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (711,"2004-01-01",137,"PWE3 WG",1,NULL,"PWE3 WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (814,' Liaison Statement from SC 29/WG 11 to All Liaison Organizations on Progress of MPEG Standards',".htm",712);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (712,"2003-12-01",138,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (815,' Liaison Response from the IETF CCAMP WG to ITU-T SG 15, Q.14/15 Regarding ASON',".html",713);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (713,"2003-12-01",27,"ITU-T SG 15, Q.14/15",1,NULL,"ITU-T SG 15, Q.14/15");
insert into uploads (file_id,file_title,file_extension,detail_id) values (816,' Liaison Statement to IETF regarding translation of IETF xDSL MIBs for use with OMCI',".html",714);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (714,"2003-12-01",139,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (817,' Liaison Statement To IETF Transport Area on Change Procedures for RSVP ',".html",715);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (715,"2003-12-01",73,"IETF Transport Area",1,NULL,"IETF Transport Area");
insert into uploads (file_id,file_title,file_extension,detail_id) values (818,' Liaison statement to IETF regarding translation of IETF xDSL MIBs for use with OMCI',".html",716);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (716,"2003-12-01",73,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (819,' Liaison Response Regarding Liaison Statement on RSVP Change Process',".txt",717);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (717,"2003-12-01",73,"IETF Transport Area",1,NULL,"IETF Transport Area");
insert into uploads (file_id,file_title,file_extension,detail_id) values (820,' Liaison Statement on RSVP Change Process',".txt",718);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (718,"2003-12-01",140,"ITU-T SG 15",1,NULL,"ITU-T SG 15");
insert into uploads (file_id,file_title,file_extension,detail_id) values (821,' Announcement of Consent for Q.811 and Q.812 (LOWER/UPPER LAYER PROTOCOL PROFILES FOR THE Q AND X INTERFACE)',".html",719);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (719,"2003-11-01",66,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (822,' Structured Probable Cause',".html",720);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (720,"2003-11-01",66,"IETF DISMAN WG",1,NULL,"IETF DISMAN WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (823,' T1S1 requirements for a solution to DTMF Digit Collection',".pdf",721);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (721,"2003-11-01",141,"IETF Transport Area",1,NULL,"IETF Transport Area");
insert into uploads (file_id,file_title,file_extension,detail_id) values (824,' TDM - MPLS network internetworking',".htm",722);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (722,"2003-11-01",142,"IETF PWE3 WG",1,NULL,"IETF PWE3 WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (825,' Re: draft-ietf-aaa-diameter-nasreq-13a.txt',".pdf",723);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (723,"2003-11-01",104,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (826,' Re: DMU (Dynamic Mobile-IP Key Update',".pdf",724);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (724,"2003-11-01",104,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (827,'Response to Liaison on Alarm MIB ',".txt",725);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (725,"2003-10-01",143,"ITU-T SG 4",1,NULL,"ITU-T SG 4");
insert into uploads (file_id,file_title,file_extension,detail_id) values (828,' Liaison Statement from the ATM Forum to the IETF PWE3',".html",726);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (726,"2003-10-01",4,"IETF PWE3",1,NULL,"IETF PWE3");
insert into uploads (file_id,file_title,file_extension,detail_id) values (829,' ASON Status',".html",727);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (727,"2003-10-01",73,"IETF CCAMP WG and Routing Area Directors",1,NULL,"IETF CCAMP WG and Routing Area Directors");
insert into uploads (file_id,file_title,file_extension,detail_id) values (830,' Liaison Statement to IETF CCAMP on RSVP-TE and CR-LDP',".html",728);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (728,"2003-10-01",73,"IETF CCAMP",1,NULL,"IETF CCAMP");
insert into uploads (file_id,file_title,file_extension,detail_id) values (831,' Liaison Statement - Optical Transport Networks & Technologies Standardization Work Plan, Issue 4',".html",729);
insert into uploads (file_id,file_title,file_extension,detail_id) values (832,'Attachement - Optical Transport Networks & Technologies Standardization Work Plan, Issue 4 ',".html",729);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (729,"2003-10-01",73,"IETF (Sub-IP & Transport Areas)",1,NULL,"IETF (Sub-IP & Transport Areas)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (833,' Liaison Statement: Proposal for Signalling Security Requirements at PSTN Interconnection with VoIP networks',".pdf",730);
insert into uploads (file_id,file_title,file_extension,detail_id) values (834,' Delayed Contribution 101: Proposal for Signalling Security Requirements at PSTN Interconnection with VoIP networks',".pdf",730);
insert into uploads (file_id,file_title,file_extension,detail_id) values (835,' Draft ITU-T Recommendation X.805 (Formerly X.css), Security architecture for systems providing end-to-end communications',".pdf",730);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (730,"2003-09-01",75,"ITU-T SG 4, 9, 11, 13, 16 and IETF",1,NULL,"ITU-T SG 4, 9, 11, 13, 16 and IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (836,' Frame relay services over MPLS core networks',".pdf",731);
insert into uploads (file_id,file_title,file_extension,detail_id) values (837,' Draft new recommendation X.84 - support frame relay services over MPLS core networks',".pdf",731);
insert into uploads (file_id,file_title,file_extension,detail_id) values (838,' Working text for a proposed amendment to draft new recommendation X.84',".pdf",731);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (731,"2003-09-01",75,"IETF PWE3 Working Group",1,NULL,"IETF PWE3 Working Group");
insert into uploads (file_id,file_title,file_extension,detail_id) values (839,' MPLS Signalling Protocols',".pdf",732);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (732,"2003-08-01",113,"IETF Sub IP Area",1,NULL,"IETF Sub IP Area");
insert into uploads (file_id,file_title,file_extension,detail_id) values (840,' The Liaison Statement to on the ITU-T IP Project',".pdf",733);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (733,"2003-08-01",113,"ITU-T SGs, ITU-R WGs, ITU-D SG2 and the IETF",1,NULL,"ITU-T SGs, ITU-R WGs, ITU-D SG2 and the IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (841,' Communication of Y.MPLSperf (file #2)',".pdf",734);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (734,"2003-08-01",113,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (842,' Communication of Y.MPLSperf',".pdf",735);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (735,"2003-08-01",113,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (843,' ATM and TDM-MPLS network interworking- user plane interworking',".pdf",736);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (736,"2003-08-01",113,"IETF (PWE3 WG)",1,NULL,"IETF (PWE3 WG)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (844,' ATM Forum Liaison Statement',".txt",737);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (737,"2003-07-01",4,"IETF-PWE3",1,NULL,"IETF-PWE3");
insert into uploads (file_id,file_title,file_extension,detail_id) values (845,' Address Space Relationships in ASON',".htm",738);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (738,"2003-06-01",73,"IETF CCAMP WG and Sub IP Directors",1,NULL,"IETF CCAMP WG and Sub IP Directors");
insert into uploads (file_id,file_title,file_extension,detail_id) values (846,' Proposed Template for Assessment of Specific Protocols Against ITU-T G.8080 and G.7715 Recommendations',".htm",739);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (739,"2003-06-01",73,"IETF CCAMP WG and Sub IP Directors",1,NULL,"IETF CCAMP WG and Sub IP Directors");
insert into uploads (file_id,file_title,file_extension,detail_id) values (847,' Draft G. 7715.1 (Attachment for Liaison Statement to IETF on definition of ASON Routing Requirements)',".htm",740);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (740,"2003-06-01",73,"IETF CCAMP WG and Sub IP Directors",1,NULL,"IETF CCAMP WG and Sub IP Directors");
insert into uploads (file_id,file_title,file_extension,detail_id) values (848,' Liaison Statement to IETF on definition of ASON Routing Requirements',".htm",741);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (741,"2003-06-01",73,"IETF CCAMP WG and Sub IP Directors",1,NULL,"IETF CCAMP WG and Sub IP Directors");
insert into uploads (file_id,file_title,file_extension,detail_id) values (849,'Liaison Statement To IETF on ASON Signaling Protocol Extensions',".pdf",742);
insert into uploads (file_id,file_title,file_extension,detail_id) values (850,'Liaison Statement To IETF on ASON Signaling Protocol Extensions updated Living List',".pdf",742);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (742,"2003-06-01",144,"IETF CCAMP WG and Sub-IP Area Directors",1,NULL,"IETF CCAMP WG and Sub-IP Area Directors");
insert into uploads (file_id,file_title,file_extension,detail_id) values (851,' RFC 2916 is about to be revised',".txt",743);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (743,"2003-06-01",145,"ITU-T SG 2",1,NULL,"ITU-T SG 2");
insert into uploads (file_id,file_title,file_extension,detail_id) values (852,' Security for Management Interfaces to Transport Network Elements',".pdf",744);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (744,"2003-06-01",25,"IETF Operations and Management Area",1,NULL,"IETF Operations and Management Area");
insert into uploads (file_id,file_title,file_extension,detail_id) values (853,'Minutes from the June 17, 2003 IETF/W3C teleconference',".html",745);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (745,"2003-06-01",7,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (854,' RE: Liaison statement from ITU-T Q.11/13 to IETF (mobileip, mpls WGs) on "Draft Recommendation Y.MIPoMPLS (Mobile IP Services over MPLS)" ',".txt",746);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (746,"2003-06-01",146,"ITU-T SG 13",1,NULL,"ITU-T SG 13");
insert into uploads (file_id,file_title,file_extension,detail_id) values (855,' Draft Recommendation Y.MIPoMPLS (Mobile IP Services over MPLS) for consent (Liaison Statement)',".pdf",747);
insert into uploads (file_id,file_title,file_extension,detail_id) values (856,' Draft new Recommendation Y.MIPoMPLS (Document)',".pdf",747);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (747,"2003-06-01",113,"IETF mobileip WG and mpls WG",1,NULL,"IETF mobileip WG and mpls WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (857,' LS to 3GPP, 3GPP2 and IETF on Transport Layer for MSC-VBR and EV',".pdf",748);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (748,"2003-05-01",147,"IETF avt and mmusic WG",1,NULL,"IETF avt and mmusic WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (858,' Final Report of the Workshop on Telecommunications for Disaster Relief',".pdf",749);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (749,"2003-05-01",74,"IETF ieprep WG",1,NULL,"IETF ieprep WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (859,' Avoiding Conflicts Between 3GPP2 and IETF Meetings',".pdf",750);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (750,"2003-05-01",104,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (860,' T1M1s New Primary Method of Operation and Increased Collaboration Opportunities ',".txt",751);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (751,"2003-05-01",148,"IETF O&M Area",1,NULL,"IETF O&M Area");
insert into uploads (file_id,file_title,file_extension,detail_id) values (861,' Sigtran WG Liaison Response: New Recommendation G.769',".txt",752);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (752,"2003-05-01",149,"ITU-T SG 15",1,NULL,"ITU-T SG 15");
insert into uploads (file_id,file_title,file_extension,detail_id) values (862,' Input to IETF EAP Working Group on Methods and Key Strength',".txt",753);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (753,"2003-04-01",101,"EAP Working Group",1,NULL,"EAP Working Group");
insert into uploads (file_id,file_title,file_extension,detail_id) values (863,' Liaison from T1X1 to IETF ccamp regarding draft-ietf-ccamp-lmp-test-sdh-02.txt',".pdf",754);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (754,"2003-04-01",150,"IETF ccamp WG",1,NULL,"IETF ccamp WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (864,'Minutes from the March 13, 2003 IETF/W3C teleconference',".html",755);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (755,"2003-03-01",7,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (865,' Transport of TDM over MPLS networks',".txt",756);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (756,"2003-02-01",151,"PWE3 WG",1,NULL,"PWE3 WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (866,' IETF decision to focus on RSVP-TE as the basis for constraint-based LSP management IETF has decided to focus on RSVP-TE as the basis for constraint-based LSP management ',".txt",757);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (757,"2003-02-01",152,"ITU-T SG 13, SG 15",1,NULL,"ITU-T SG 13, SG 15");
insert into uploads (file_id,file_title,file_extension,detail_id) values (867,' Framework of new Recommendation O.iptest',".htm",758);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (758,"2003-02-01",66,"Transport ADs (Allison Mankin and Scott Bradner)",1,NULL,"Transport ADs (Allison Mankin and Scott Bradner)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (868,'Use of RFC 3430',".txt",759);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (759,"2003-02-01",66,"OPS ADs (Randy Bush and Bert Wijnen)",1,NULL,"OPS ADs (Randy Bush and Bert Wijnen)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (869,' Announcement of the consent of M.3017 (Framework for the Integrated Management of Hybrid Circuit/Packet Networks)',".htm",760);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (760,"2003-02-01",66,"OPS ADs (Randy Bush and Bert Wijnen)",1,NULL,"OPS ADs (Randy Bush and Bert Wijnen)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (870,' Liaison on Alarm MIB',".txt",761);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (761,"2003-02-01",66,"DISMAN WG",1,NULL,"DISMAN WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (871,' Liaison Statement To IETF CCAMP WG and Sub-IP Area Directors From WP3/15 on ASON Routing Activities',".htm",762);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (762,"2003-01-01",73,"CCAMP WG",1,NULL,"CCAMP WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (872,' Optical Transport Networks & Technologies Standardization Work Plan, Issue 3',".htm",763);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (763,"2003-01-01",73,"SUB-IP and Transport Areas",1,NULL,"SUB-IP and Transport Areas");
insert into uploads (file_id,file_title,file_extension,detail_id) values (873,'Liaison Statement To IETF CCAMP WG and Sub-IP Area Directors From WP3/15 on ASON Routing Activities',".htm",764);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (764,"2003-01-01",73,"CCAMP WG",1,NULL,"CCAMP WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (874,' ASON Status and GMPLS Protocol Support for Restoration/Re-routing Capabilities',".htm",765);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (765,"2003-01-01",73,"CCAMP WG",1,NULL,"CCAMP WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (875,' Input on SDH and OTN Discovery Mechanisms',".htm",766);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (766,"2003-01-01",73,"CCAMP WG",1,NULL,"CCAMP WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (876,'Information of a new Recommendation G.769',".htm",767);
insert into uploads (file_id,file_title,file_extension,detail_id) values (877,'Attachment to above: D-711 E Transmission schemes of SS7 Signaling optimised for IP-CME',".htm",767);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (767,"2003-01-01",73,"SIGTRAN WG",1,NULL,"SIGTRAN WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (878,'CDMA2000 wireless IP network specification (P.S0001-C) - Baseline specifications',".html",768);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (768,"2003-01-01",104,"Various IETF WGs",1,NULL,"Various IETF WGs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (879,'e164.arpa domain management LIAISON STATEMENT',".txt",769);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (769,"2002-12-01",64,"IAB",1,NULL,"IAB");
insert into uploads (file_id,file_title,file_extension,detail_id) values (880,'Administrative aspects of ENUM - Security LIAISON STATEMENT',".txt",770);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (770,"2002-12-01",64,"IAB",1,NULL,"IAB");
insert into uploads (file_id,file_title,file_extension,detail_id) values (881,'Request for comments on proposed draft Amendment 1 to X.85/Z.1321, bit oriented method for LAPS as Annex D (PDF File)',".pdf",771);
insert into uploads (file_id,file_title,file_extension,detail_id) values (882,'Attachment to above (PDF File)',".pdf",771);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (771,"2002-12-01",75,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (883,'Liaison statement from IETF AVT working group to ISO/IEC/JTC1/SC29/WG11',".txt",772);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (772,"2002-12-01",153,"SC29/WG11",1,NULL,"SC29/WG11");
insert into uploads (file_id,file_title,file_extension,detail_id) values (884,'3GPP final response on IMS interoperability concerns',".htm",773);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (773,"2002-12-01",99,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (885,'Administrative aspects of ENUM - Security',".htm",774);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (774,"2002-12-01",64,"IAB/ISOC",1,NULL,"IAB/ISOC");
insert into uploads (file_id,file_title,file_extension,detail_id) values (886,'e164.arpa domain management',".htm",775);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (775,"2002-12-01",64,"ISOC/IAB Liaison",1,NULL,"ISOC/IAB Liaison");
insert into uploads (file_id,file_title,file_extension,detail_id) values (887,'Recommendation E.360 QoS routing and related traffic engineering methods for IP-, ATM- and TDM-based multiservice networks',".htm",776);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (776,"2002-12-01",64,"TEWG, MPLS, CCAMP WGs",1,NULL,"TEWG, MPLS, CCAMP WGs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (888,'L1 VPN service requirements and architecture',".htm",777);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (777,"2002-11-01",113,"PPVPN WG",1,NULL,"PPVPN WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (889,'Liaison statement on the ITU-T IP Project ',".pdf",778);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (778,"2002-11-01",113,"IETF (and others)",1,NULL,"IETF (and others)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (890,'ATM-MPLS Network Interworking ',".pdf",779);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (779,"2002-11-01",113,"PWE WG",1,NULL,"PWE WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (891,'Minutes from the November 12, 2002 IETF/W3C teleconference',".html",780);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (780,"2002-11-01",7,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (892,'ITU liaison statement',".html",781);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (781,"2002-10-01",73,"Scott Bradner",1,NULL,"Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (893,'Liaison to multiple SDOs requesting input for "Media Coding Summary Database" project',".htm",782);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (782,"2002-10-01",74,"",1,NULL,"");
insert into uploads (file_id,file_title,file_extension,detail_id) values (894,'New Question on Use of Public Telecommunication Services for Emergency and Disaster Relief Operations',".htm",783);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (783,"2002-10-01",74,"IEPREP WG",1,NULL,"IEPREP WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (895,'Liaison Statement on Interoperability Issues and SIP in IMS',".txt",784);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (784,"2002-09-01",154,"3GPP",1,NULL,"3GPP");
insert into uploads (file_id,file_title,file_extension,detail_id) values (896,'3GPP response to Liaison Statement on Interoperability Issues and SIP in IMS',".txt",785);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (785,"2002-09-01",99,"SIP, SIPPING, SIMPLE WGs",1,NULL,"SIP, SIPPING, SIMPLE WGs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (897,'Liaison statement about new Wireless LAN Interworking Group (WIG)',".htm",786);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (786,"2002-09-01",155,"IESG",1,NULL,"IESG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (898,'Liaison Statement from SC 29/WG 11 to IETF on Carriage of MPEG-4 Content on IP Networks',".txt",787);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (787,"2002-09-01",156,"IETF",1,NULL,"IETF");
insert into uploads (file_id,file_title,file_extension,detail_id) values (899,'Request for the assignment of a reserved label value of 14 for MPLS OAM packet identification',".txt",788);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (788,"2002-07-01",113," SubIP ADs (sob@harvard.edu,bwijnen@lucent.com)",1,NULL," SubIP ADs (sob@harvard.edu,bwijnen@lucent.com)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (900,'Response to Communication from IETF on MPLS OAM packet identification',".txt",789);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (789,"2002-07-01",113," SubIP ADs (sob@harvard.edu,bwijnen@lucent.com)",1,NULL," SubIP ADs (sob@harvard.edu,bwijnen@lucent.com)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (901,'SG 13 work on interworking with MPLS',".txt",790);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (790,"2002-07-01",113,"PWE3 WG",1,NULL,"PWE3 WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (902,'ATM-MPLS Interworking activities in ITU-T',".txt",791);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (791,"2002-07-01",113,"PWE3 WG",1,NULL,"PWE3 WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (903,'Voice Services over MPLS',".txt",792);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (792,"2002-07-01",113,"PWE3 WG",1,NULL,"PWE3 WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (904,'AVT WG''s response to SC 29/WG 11 to IETF on the Carriage of MPEG-4 Content on IP Networks',".txt",793);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (793,"2002-06-01",153,"SC 29/WG11",1,NULL,"SC 29/WG11");
insert into uploads (file_id,file_title,file_extension,detail_id) values (905,'3GPP Diameter Charging & Credit Control Application',".htm",794);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (794,"2002-06-01",99,"AAA WG Chairs",1,NULL,"AAA WG Chairs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (906,'Communication re: SIP - BICC/ISUP Interworking',".txt",795);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (795,"2002-06-01",70,"SIP aand SIPPING WGs",1,NULL,"SIP aand SIPPING WGs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (907,'Appointment of Eric Edwards as Liaison',".txt",796);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (796,"2002-05-01",157,"",1,NULL,"");
insert into uploads (file_id,file_title,file_extension,detail_id) values (908,'Optical Intra-Carrier Network-Network Interface project',".html",797);
insert into uploads (file_id,file_title,file_extension,detail_id) values (909,'OIF Initial Requirements',".html",797);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (797,"2002-05-01",25,"",1,NULL,"");
insert into uploads (file_id,file_title,file_extension,detail_id) values (910,'Response to clarification given on usability of Sigtran in G.799.1',".htm",798);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (798,"2002-05-01",73,"Lyndon Ong (lyong@ciena.com)",1,NULL,"Lyndon Ong (lyong@ciena.com)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (911,'Liaison Statement from SC 29/WG 11 to IETF on the Carriage of MPEG-4 Content on IP Networks',".htm",799);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (799,"2002-05-01",158,"AVT WG",1,NULL,"AVT WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (912,'ENUM LIAISON ON IAB INSTRUCTIONS TO RIPE-NCC ',".htm",800);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (800,"2002-05-01",64,"IAB",1,NULL,"IAB");
insert into uploads (file_id,file_title,file_extension,detail_id) values (913,'APPROVAL OF INTERIM PROCEDURES AND ASSURANCES OF STABILITY',".htm",801);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (801,"2002-05-01",64,"IAB",1,NULL,"IAB");
insert into uploads (file_id,file_title,file_extension,detail_id) values (914,' Communication Statement to IETF CCAMP Working Group on signalling protocol work in Q. 14/15',".html",802);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (802,"2002-05-01",73,"IETF ccamp WG",1,NULL,"IETF ccamp WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (915,' Communication Statement to Optical Internetworking Forum (OIF) on automatic discovery work in Q.14/15',".html",803);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (803,"2002-05-01",73,"Optical Internetworking Forum (OIF) Architecture and Signalling WGs CC: IETF ccamp Working Group",1,NULL,"Optical Internetworking Forum (OIF) Architecture and Signalling WGs CC: IETF ccamp Working Group");
insert into uploads (file_id,file_title,file_extension,detail_id) values (916,'ENUM Liaison',".html",804);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (804,"2002-04-01",64,"IAB",1,NULL,"IAB");
insert into uploads (file_id,file_title,file_extension,detail_id) values (917,'Additional input regarding the use of M.3100 probable causes for the ITU Alarm MIB',".txt",805);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (805,"2002-04-01",66,"DISMAN WG",1,NULL,"DISMAN WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (918,'Response to "Communication on the status of the request on the assignment of a reserved label value for MPLS OAM packet identification"',".txt",806);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (806,"2002-04-01",159,"Completes action above Scott Bradner, Area co-Director (sob@harvard.edu)",1,NULL,"Completes action above Scott Bradner, Area co-Director (sob@harvard.edu)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (919,'Liaison Statement to IETF on status of ECTP project',".txt",807);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (807,"2002-03-01",68,"IESG",1,NULL,"IESG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (920,'ITU-SG16 comments on draft-parsons-itu-t38-reg-00.txt',".txt",808);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (808,"2002-03-01",113,"Scott Bradner (sob@harvard.edu)",1,NULL,"Scott Bradner (sob@harvard.edu)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (921,'ITU-SG16 comments on draft-mule-sip-t38callflows-02.txt',".txt",809);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (809,"2002-03-01",113,"Scott Bradner (sob@harvard.edu)",1,NULL,"Scott Bradner (sob@harvard.edu)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (922,'ITU-SG16 new question on Emergency Telecommunications Service (ETS)',".txt",810);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (810,"2002-03-01",113,"Scott Bradner (sob@harvard.edu)",1,NULL,"Scott Bradner (sob@harvard.edu)");
insert into uploads (file_id,file_title,file_extension,detail_id) values (923,'Liaison Statement from SC 29/WG 11 to IETF on Transport of MPEG-4 Content over IP [SC 29/WG 11 N 4663]',".txt",811);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (811,"2002-03-01",158,"",1,NULL,"");
insert into uploads (file_id,file_title,file_extension,detail_id) values (924,'Liaison Statement from SC 29/WG 1 to IETF, seeking IETF contributions to JPEG 2000 Part 9 JPIP [SC 29/WG 1 N 2551]',".txt",812);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (812,"2002-03-01",160,"",1,NULL,"");
insert into uploads (file_id,file_title,file_extension,detail_id) values (925,'Memo from ITU-T Study Group 13 requesting assignment of a reserved label value for MPLS OAM packet identification',".txt",813);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (813,"2002-02-01",113," Scott Bradner (sob@harvard.edu) Done",1,NULL," Scott Bradner (sob@harvard.edu) Done");
insert into uploads (file_id,file_title,file_extension,detail_id) values (926,' Detector-Controller Interface (DCI)',".html",814);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (814,"2002-02-01",73,"IETF ccamp WG",1,NULL,"IETF ccamp WG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (927,'Memo from ATM Forum requesting status of specific documents',".txt",815);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (815,"2002-02-01",4,"Tom Taylor (taylor@nortelnetworks.com), Megaco WG Chair",1,NULL,"Tom Taylor (taylor@nortelnetworks.com), Megaco WG Chair");
insert into uploads (file_id,file_title,file_extension,detail_id) values (928,'Response to above memo from ATM Forum',".txt",816);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (816,"2002-02-01",4,"DONE",1,NULL,"DONE");
insert into uploads (file_id,file_title,file_extension,detail_id) values (929,'Memo from ATM Forum requesting comments on version 2 of their ATM-MPLS-ATM Network Interworking specification.',".html",817);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (817,"2002-02-01",4," Danny McPherson, Luca Martini (danny@tcb.net,luca@level3.net), PWE3 WG Chairs",1,NULL," Danny McPherson, Luca Martini (danny@tcb.net,luca@level3.net), PWE3 WG Chairs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (930,'Communication Statement to IETF CCAMP Working Group on signalling protocol work in Q.14/15',".html",818);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (818,"2002-02-01",161,"(kireeti@juniper.net,vijay@umbc.edu) Kireeti Kompella , Vijay Gill CCAMP WG Chairs",1,NULL,"(kireeti@juniper.net,vijay@umbc.edu) Kireeti Kompella , Vijay Gill CCAMP WG Chairs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (931,'Communication Statement to IETF CCAMP Working Group on Virtual Backplane Interface (VBI) in Q.15',".html",819);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (819,"2002-02-01",162,"(kireeti@juniper.net,vijay@umbc.edu) Kireeti Kompella , Vijay Gill CCAMP WG Chairs",1,NULL,"(kireeti@juniper.net,vijay@umbc.edu) Kireeti Kompella , Vijay Gill CCAMP WG Chairs");
insert into uploads (file_id,file_title,file_extension,detail_id) values (932,'Letter from IEEE 802.11 to IETF/IESG',".txt",820);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (820,"2002-02-01",101,"IESG",1,NULL,"IESG");
insert into uploads (file_id,file_title,file_extension,detail_id) values (933,'liaison statement to IETF (SC 29 N 4559 and 4561)',".txt",821);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (821,"2001-12-01",163,"Harald Alvestrand",1,NULL,"Harald Alvestrand");
insert into uploads (file_id,file_title,file_extension,detail_id) values (934,'Liaison Statement to the IETF AVT Working Group on MPEG-4 on IP',".htm",822);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (822,"2001-12-01",164,"",1,NULL,"");
insert into uploads (file_id,file_title,file_extension,detail_id) values (935,'Liaison Letter to IETF regarding JVT Video Packetization',".htm",823);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (823,"2001-12-01",165,"",1,NULL,"");
insert into uploads (file_id,file_title,file_extension,detail_id) values (936,'CODING OF MOVING PICTURES AND ASSOCIATED AUDIO INFORMATION',".htm",824);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (824,"2001-12-01",163,"Harald Alvestrand",1,NULL,"Harald Alvestrand");
insert into uploads (file_id,file_title,file_extension,detail_id) values (937,'Sigtran WG response to ITU-T SG15',".txt",825);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (825,"2001-12-01",166,"(lyong@ciena.com)Lyndon Ong",1,NULL,"(lyong@ciena.com)Lyndon Ong");
insert into uploads (file_id,file_title,file_extension,detail_id) values (938,'Memo from ITU-T Study Group 7 to the SMIng Working Group',".htm",826);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (826,"2001-12-01",167,"(bwijnen@lucent.com) Bert Wijnen",1,NULL,"(bwijnen@lucent.com) Bert Wijnen");
insert into uploads (file_id,file_title,file_extension,detail_id) values (939,' New Recommendations for Automatically Switched Optical Networks',".txt",827);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (827,"2001-10-01",168,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (940,' Optical Transport Networks & Technologies Standardization Work Plan, Issue 1',".txt",828);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (828,"2001-10-01",168,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (941,'SDH Signal and Group Structures',".txt",829);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (829,"2001-10-01",168,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (942,' Request for comments on G.799.1 -- handling of Signalling System No.7 associated signalling links by a TIGIN gateway',".txt",830);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (830,"2001-10-01",168,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (943,' Liaison Statement regarding Digital Rights Standards work in the Internet Research Task Force',".htm",831);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (831,"2001-03-01",169,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (944,' Intellectual Property Management and Protection in MPEG Standards',".htm",832);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (832,"2001-03-01",169,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (945,' Re-issue of the Call for Requirements for a Rights Data Dictionary and a Rights Expression Language',".htm",833);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (833,"2001-03-01",169,"(sob@harvard.edu)Scott Bradner",1,NULL,"(sob@harvard.edu)Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (946,' MPEG-21 Requirements for a Rights Data Dictionary and a Rights Expression Language',".txt",834);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (834,"2001-03-01",169,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (947,'DRAFT REVISED ITU-T RECOMMENDATION X.85/Y.1321: "IP OVER SDH USING LAPS" (Temporary Document 2066/Rev.1)',".htm",835);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (835,"2001-02-01",170,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (948,'DRAFT AMENDMENT 1 TO ITU-T RECOMMENDATION X.85/Y.1321 (2000) (Temporary Document 2045/Rev.3)',".htm",836);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (836,"2001-02-01",170,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (949,'RESPONSE TO COMMENTS ON X.85/Y.1321 (Temporary Document 2031/Rev.3)',".htm",837);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (837,"2001-02-01",170,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (950,'REVISED DRAFT TEXT OF THE ECTP SPECIFICATION FOR ITU-T CONSENT AND JTC 1 FCD BALLOT  (Temporary Document 2032/Rev.2)',".htm",838);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (838,"2001-02-01",170,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (951,'REQUEST FOR CONSIDERATION OF LATEST TEXT OF ECTP (Temporary Document 2058/Rev.1)',".htm",839);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (839,"2001-02-01",170,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (952,'COMMUNICATION TO IETF REGARDING ALLOCATION OF IANA INTERNET CODE POINTS FOR USE IN NSAP ADDRESSES (Temporary Document 1018/Rev.1)',".htm",840);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (840,"2001-02-01",170,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (953,'Amendment 1: Addition of the Internet protocol address format identifier (Amendment to X.213)',".htm",841);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (841,"2001-02-01",167,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (954,'COMMUNICATION TO ISOC ON IANA REGISTRATIONS FOR REC. T. 38 ANNEX D',".txt",842);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (842,"2000-02-01",171,"(sob@harvard.edu) Scott Bradner",1,NULL,"(sob@harvard.edu) Scott Bradner");
insert into uploads (file_id,file_title,file_extension,detail_id) values (955,'Cooperative Agreement Between the Internet Society and the International Organization for Standardization / International Electrotechnical Committee 1 / Sub Committee 6 (ISO/IEC JTC1/SC6)',".txt",843);
insert into liaison_detail (detail_id,submitted_date,from_id,to_body,by_secretariat,submitter_email,submitter_name) values (843,"1995-01-01",172,"ISOC",1,NULL,"ISOC");
