#!/bin/bash

program=${0##*/}
progdir=${0%/*}

cd $progdir/..				# now at trunk/

test/test-setup			# create a patched django for test purposes, and more

test/run-pyflakes ietf

# Trap keyboard interrupt to ensure the test/teardown is run if we interrupt the tests
trap 'echo "$program($LINENO): Caught Interrupt"' INT 

# run tests with our patched django
PYTHONPATH=test:test/lib URLPREFIX="$*" python ietf/manage.py test

# reset keyboard interrupt trap
trap INT

test/test-teardown

