#!/bin/bash

set -x

program=${0##*/}
progdir=${0%/*}

cd $progdir/..				# now at trunk/

test/test-setup			# create a patched django for test purposes, and more

test/run-pyflakes ietf

PYTHONPATH=test/lib python ietf/manage.py test # run tests with our patched django

test/test-teardown

