#!/bin/bash

function filter() {
python -c '
import sys
file = open(sys.argv[1])
excludes = [line.strip() for line in file.readlines()]
for line in sys.stdin:
    if not line.strip() in excludes:
	sys.stdout.write(line)
' "$@"
}

pyflakes "$@" | filter "${0%/*}/pyflakes.exclude"