# Generated by Django 4.2.3 on 2023-07-26 18:41

from django.db import migrations

from ietf.name.models import FeedbackTypeName

def add_obe(apps, schema_editor):
    name = FeedbackTypeName(slug='obe', name='Overcome by events')
    name.save()

class Migration(migrations.Migration):
    dependencies = [
        ("name", "0003_populate_telechatagendasectionname"),
    ]

    operations = [
        migrations.RunPython(add_obe),
    ]
