# Generated by Django 4.2.2 on 2023-06-14 20:39

from django.db import migrations


def forward(apps, schema_editor):
    DocTypeName = apps.get_model("name", "DocTypeName")
    DocTypeName.objects.get_or_create(
        slug="rfc",
        name="RFC",
        used=True,
        prefix="rfc",
    )
    

class Migration(migrations.Migration):
    dependencies = [
        ("name", "0003_populate_telechatagendasectionname"),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
