# Generated by Django 4.2.4 on 2023-08-24 14:51

from django.db import migrations


def forward(apps, schema_editor):
    SourceFormatName = apps.get_model("name", "SourceFormatName")
    SourceFormatName.objects.create(
        slug="xml-v3", name="RFCXML v3", desc="RFCXML v3", used=True,
    )
    SourceFormatName.objects.create(
        slug="xml-v2", name="RFCXML v2", desc="RFCXML v2", used=True
    )
    SourceFormatName.objects.create(
        slug="md", name="Markdown", desc="Markdown", used=True
    )
    SourceFormatName.objects.create(
        slug="txt", name="plaintext", desc="plaintext", used=True
    )


def reverse(apps, schema_editor):
    SourceFormatName = apps.get_model("name", "SourceFormatName")
    SourceFormatName.objects.filter(slug__in=["xml-v3", "xml-v2", "md", "txt"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("name", "0007_sourceformatname_tlpboilerplatechoicename"),
    ]

    operations = [migrations.RunPython(forward, reverse)]
