# Generated by Django 4.2.4 on 2023-08-24 14:52

from django.db import migrations


def forward(apps, schema_editor):
    TlpBoilerplateChoiceName = apps.get_model("name", "TlpBoilerplateChoiceName")
    TlpBoilerplateChoiceName.objects.create(
        slug="trust200902",
        name="trust200902",
        desc="Notice from the text of section 6.b of the TLP",
        used=True,
    )
    TlpBoilerplateChoiceName.objects.create(
        slug="noModificationTrust200902",
        name="noModificationTrust200902",
        desc="Notice from the text of sections 6.b and 6.c.i of the TLP "
             "(may be appropriate when republishing standards produced by a standards body "
             "other than the IETF, industry consortia, or companies, typically as an Informational "
             "RFC)",
        used=True,
    )
    TlpBoilerplateChoiceName.objects.create(
        slug="noDerivativesTrust200902",
        name="noDerivativesTrust200902",
        desc="Notice from the text of sections 6.b and 6.c.ii of the TLP "
             "(may be used on I-Ds intended to provide background information to educate"
             "and facilitate discussions within IETF working groups but not"
             "intended to be published as RFCs)",
        used=True,
    )
    TlpBoilerplateChoiceName.objects.create(
        slug="pre5378Trust200902",
        name="pre5378Trust200902",
        desc="Notice from the text of sections 6.b and 6.c.iii of the TLP "
             "(see TLP Modification of 15 Feb 2009 section of Trust FAQ)",
        used=True,
    )
    TlpBoilerplateChoiceName.objects.create(
        slug="trust200811",
        name="trust200811",
        desc="Historic value similar to trust200902",
        used=True,
    )
    TlpBoilerplateChoiceName.objects.create(
        slug="noModificationTrust200811",
        name="noModificationTrust200811",
        desc="Historic value similar to noModificationTrust200902",
        used=True,
    )
    TlpBoilerplateChoiceName.objects.create(
        slug="noDerivativesTrust200811",
        name="noDerivativesTrust200811",
        desc="Historic value similar to noDerivativesTrust200902",
        used=True,
    )


def reverse(apps, schema_editor):
    TlpBoilerplateChoiceName = apps.get_model("name", "TlpBoilerplateChoiceName")
    TlpBoilerplateChoiceName.objects.filter(
        slug__in=[
            "trust200902",
            "noModificationTrust200902",
            "noDerivativesTrust200902",
            "pre5378Trust200902",
            "trust200811",
            "noModificationTrust200811",
            "noDerivativesTrust200811",
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("name", "0008_populate_sourceformatname"),
    ]

    operations = [migrations.RunPython(forward, reverse)]
