# Generated by Django 4.2.2 on 2023-06-14 20:39

from django.db import migrations


def forward(apps, schema_editor):
    DocTypeName = apps.get_model("name", "DocTypeName")
    DocTypeName.objects.get_or_create(
        slug="rfc",
        name="RFC",
        used=True,
        prefix="rfc",
    )
    
    DocRelationshipName = apps.get_model("name", "DocRelationshipName")
    DocRelationshipName.objects.get_or_create(
        slug="became_rfc",
        name="became RFC",
        used=True,
        revname="came from draft",
    )

class Migration(migrations.Migration):
    dependencies = [
        ("name", "0009_iabworkshops"),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
