# Generated by Django 4.2.11 on 2024-03-16 03:07

from django.db import migrations

def forward(apps, schema_editor):
    ExtResourceName = apps.get_model("name", "ExtResourceName")
    ExtResourceTypeName = apps.get_model("name", "ExtResourceTypeName")
    urlType = ExtResourceTypeName.objects.filter(slug="url")[0]
    print(urlType)
    ExtResourceName.objects.create(
        slug="related_test_cases",
        name="Related test cases",
        desc="Related test cases",
        used=True,
        order=0,
        type=urlType
    )

def reverse(apps, schema_editor):
    ExtResourceName = apps.get_model("name", "ExtResourceName")

    ExtResourceName.objects.filter(slug="related_test_cases").delete()

class Migration(migrations.Migration):

    dependencies = [
        ("name", "0013_narrativeminutes"),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
