# Copyright The IETF Trust 2025, All Rights Reserved# Generated by Django 4.2.21 on 2025-05-30 16:35

from django.db import migrations


def forward(apps, schema_editor):
    RoleName = apps.get_model("name", "RoleName")
    RoleName.objects.filter(slug__in=["liaison_contact", "liaison_cc_contact"]).update(
        used=False
    )
    RoleName.objects.get_or_create(
        slug="liaison_coordinator",
        defaults={
            "name": "Liaison Coordinator",
            "desc": "Coordinates liaison handling for the IAB",
        },
    )


def reverse(apps, schema_editor):
    RoleName = apps.get_model("name", "RoleName")
    RoleName.objects.filter(slug__in=["liaison_contact", "liaison_cc_contact"]).update(
        used=True
    )
    RoleName.objects.filter(slug="liaison_coordinator").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("name", "0017_populate_new_reg_names"),
    ]

    operations = [migrations.RunPython(forward, reverse)]
