# Generated by Django 2.2.20 on 2021-05-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('name', '0023_change_stream_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraintname',
            name='is_group_conflict',
            field=models.BooleanField(default=False,
                                      help_text='Does this constraint capture a conflict between groups?'),
        ),
    ]
