# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0023_add_country_continent_names'),
        ('name', '0020_add_topics'),
    ]

    operations = [
    ]
