# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 07:07
from __future__ import unicode_literals

from django.db import migrations

def forward(apps,schema_editor):
    ImportantDateName = apps.get_model('name','ImportantDateName')

    # offsets below assume meetings start on Saturday

    ImportantDateName.objects.create(
        slug='openreg',
        name='Registration Opens',
        desc='IETF Online Registration Opens',
        used=True,
        order=0,
        default_offset_days= - (13*7 - 2), # Monday
    )

    ImportantDateName.objects.create(
        slug='opensched',
        name='Scheduling Opens',
        desc='Working Group and BOF scheduling begins',
        used=True,
        order=0,
        default_offset_days= - (13*7 - 2), # Monday
    )

    ImportantDateName.objects.create(
        slug='cutoffwgreq',
        name='Cut-off WG scheduling Requests',
        desc='Cut-off date for requests to schedule Working Group Meetings at UTC 23:59',
        used=True,
        order=0,
        default_offset_days= - (6*7 + 1), # Friday
    )

    ImportantDateName.objects.create(
        slug='cutoffbofreq',
        name='Cut-off BOF scheduling Requests',
        desc='Cut-off date for BOF proposal requests to Area Directors at UTC 23:59',
        used=True,
        order=0,
        default_offset_days= - (6*7 + 1), # Friday
    )

    ImportantDateName.objects.create(
        slug='cutoffbofapprove',
        name='Cut-off BOF approval',
        desc='Cut-off date for Area Directors to approve BOFs at UTC 23:59',
        used=True,
        order=0,
        default_offset_days= - (5*7 + 1), # Friday
    )

    ImportantDateName.objects.create(
        slug='prelimagenda',
        name='Preliminary Agenda',
        desc='Preliminary Agenda published for comment',
        used=True,
        order=0,
        default_offset_days= - (4*7 + 1), # Friday
    )

    ImportantDateName.objects.create(
        slug='cutoffresched',
        name='Cut-off Reschedule Requests',
        desc='Cut-off date for requests to reschedule Working Group or BOF meetings UTC 23:59',
        used=True,
        order=0,
        default_offset_days= - (4*7 - 4), # Wednesday
    )

    ImportantDateName.objects.create(
        slug='finalagenda',
        name='Final Agenda',
        desc='Final agenda to be published',
        used=True,
        order=0,
        default_offset_days= - (3*7 + 1), # Friday
    )

    # NOTE idcutoff is targetted for the current situation where we
    # only have one draft cutoff date.. If we ever go back to a separate
    # -01 vs -00 cutoff, this one will need to be marked unused and the
    # two at then end should be marked used.

    ImportantDateName.objects.create(
        slug='idcutoff',
        name='ID Cutoff',
        desc='Internet Draft submission cut-off (for all drafts, including -00) by UTC 23:59', # TODO - get these times out of there? What if the policy changes? Old meetings should show the time used for that meeting.
        used=True,
        order=0,
        default_offset_days= - (2*7 - 2), # Monday
    )

    ImportantDateName.objects.create(
        slug='draftwgagenda',
        name='Draft Working Group Agendas',
        desc='Draft Working Group agendas due by UTC 23:59',
        used=True,
        order=0,
        default_offset_days= - (2*7 - 4), #  Wednesday
    )

    ImportantDateName.objects.create(
        slug='earlybird',
        name='Earlybird cutoff',
        desc='Early Bird registration and payment cut-off at UTC 23:59',
        used=True,
        order=0,
        default_offset_days= - (1*7 + 1), # Friday
    )

    ImportantDateName.objects.create(
        slug='revwgagenda',
        name='Revised Working Group Agendas',
        desc='Revised Working Group agendas due by UTC 23:59',
        used=True,
        order=0,
        default_offset_days= - (1*7 - 2), # Monday
    )

    ImportantDateName.objects.create(
        slug='cutoffcancel',
        name='Registration Cancellation Cut-off',
        desc='Registration cancellation cut-off at UTC 23:59',
        used=True,
        order=0,
        default_offset_days= - (1*7 - 2), # Monday
    )

    ImportantDateName.objects.create(
        slug='cutoffpre',
        name='Pre-Registration Cutoff',
        desc='Final Pre-Registration and Pre-Payment cut-off at 17:00 local meeting time',
        used=True,
        order=0,
        default_offset_days= - (0*7 + 1), # Friday
    )

    ImportantDateName.objects.create(
        slug='procsub',
        name='Proceedings Submission Cut-off',
        desc='Proceedings submission cutoff date by UTC 23:59',
        used=True,
        order=0,
        default_offset_days= (6 + 3*7), # Friday
    )

    ImportantDateName.objects.create(
        slug='revsub',
        name='Proceedings Submission Revision Cut-off',
        desc='Proceedings submission corrections cutoff date by UTC 23:59',
        used=True,
        order=0,
        default_offset_days=  (2 + 7*7), # Monday
    )

    ImportantDateName.objects.create(
        slug='00cutoff',
        name='00 ID Cutoff',
        desc='Internet Draft submission cut-off for -00 drafts by UTC 23:59', 
        used=False,
        order=0,
        default_offset_days= - (3*7 - 2), # Monday
    )

    ImportantDateName.objects.create(
        slug='01cutoff',
        name='01 ID Cutoff',
        desc='Internet Draft submission cut-off for revised (-01 and above) drafts by UTC 23:59', 
        used=False,
        order=0,
        default_offset_days= - (2*7 - 2), # Monday
    )


def reverse(apps,schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('name', '0025_add-important-dates'),
        ('meeting','0053_important_date')
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
