# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-26 05:36
from __future__ import unicode_literals

from django.db import migrations, models

def forwards(apps,schema_editor):
    DocUrlTagName = apps.get_model('name','DocUrlTagName')

    DocUrlTagName.objects.create(
        slug='wiki',
        name='Document wiki',
    )
    DocUrlTagName.objects.create(
        slug='issues',
        name='Document Issue Tracker',
    )
    DocUrlTagName.objects.create(
        slug='repository',
        name='Document Source Repository',
    )
    DocUrlTagName.objects.create(
        slug='yang-module',
        name='Extracted Yang Module',
    )
    DocUrlTagName.objects.create(
        slug='yang-impact-analysis',
        name='Yang Impact Analysis',
    )
    DocUrlTagName.objects.create(
        slug='yang-module-metadata',
        name='Yang module metadata',
    )

def backwards(apps,schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('name', '0026_popuulate-important-date-names'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocUrlTagName',
            fields=[
                ('slug', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('used', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.RunPython(forwards, backwards),
    ]


