# Copyright The IETF Trust 2021 All Rights Reserved

# Generated by Django 2.2.23 on 2021-05-21 12:48

from django.db import migrations

def forward(apps,schema_editor):
    DocTypeName = apps.get_model('name','DocTypeName')
    DocTypeName.objects.create(prefix='bofreq', slug='bofreq', name="BOF Request", desc="", used=True, order=0)

def reverse(apps,schema_editor):
    DocTypeName = apps.get_model('name','DocTypeName')
    DocTypeName.objects.filter(slug='bofreq').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('name', '0026_add_conflict_constraintnames'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
