# Generated by Django 2.2.24 on 2021-10-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0036_depopulate_timeslottypename_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslottypename',
            name='private',
        ),
    ]
