# Generated by Django 2.2.24 on 2021-10-29 06:44

from django.db import migrations


def forward(apps, schema_editor):
    TimeSlotTypeName = apps.get_model('name', 'TimeSlotTypeName')
    TimeSlotTypeName.objects.filter(slug__in=('offagenda', 'reserved')).update(used=False)


def reverse(apps, schema_editor):
    TimeSlotTypeName = apps.get_model('name', 'TimeSlotTypeName')
    TimeSlotTypeName.objects.filter(slug__in=('offagenda', 'reserved')).update(used=True)


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0037_remove_timeslottypename_private'),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
