# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-28 11:11
from __future__ import unicode_literals

from django.db import migrations

def forward(apps, schema_editor):
    MailTrigger = apps.get_model('mailtrigger','MailTrigger')
    Recipient = apps.get_model('mailtrigger', 'Recipient')
    group_added_comment = MailTrigger.objects.create(
        slug='group_added_comment',
        desc="Recipients when a comment is added to a group's history",
    )
    group_added_comment.to = Recipient.objects.filter(slug__in=[
        'group_chairs',
        'group_secretaries',
        'group_responsible_directors',
    ])

def reverse(apps, schema_editor):
    MailTrigger = apps.get_model('mailtrigger','MailTrigger')
    MailTrigger.objects.filter(slug='group_added_comment').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mailtrigger', '0010_auto_20161207_1104'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
