# Copyright The IETF Trust 2019-2020, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-04 13:12


from django.db import migrations

def forward(apps, shema_editor):
    MailTrigger = apps.get_model('mailtrigger', 'MailTrigger')
    for trigger in MailTrigger.objects.filter(slug__startswith='review_completed',slug__endswith='early'):
        trigger.cc.remove('ietf_last_call')


def reverse(apps, shema_editor):
    MailTrigger = apps.get_model('mailtrigger', 'MailTrigger')
    for trigger in MailTrigger.objects.filter(slug__startswith='review_completed',slug__endswith='early'):
        trigger.cc.add('ietf_last_call')


class Migration(migrations.Migration):

    dependencies = [
        ('mailtrigger', '0011_ietf_last_call'),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
