# Generated by Django 4.2.13 on 2024-06-24 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("person", "0002_alter_historicalperson_ascii_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Only active messages will be shown"
                    ),
                ),
                (
                    "message",
                    models.CharField(help_text="Your status message.", max_length=255),
                ),
                ("url", models.URLField()),
                (
                    "by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="person.person"
                    ),
                ),
            ],
        ),
    ]
