# Generated by Django 4.2.13 on 2024-07-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0004_remove_status_status_id_status_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
