# Generated by Django 4.2.13 on 2024-07-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0005_alter_status_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="slug",
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
