SIGNIFICANT_STATES = [
    'Adopted by a WG',
    'In WG Last Call',
    'WG Consensus: Waiting for Write-Up',
    'Parked WG Document',
    'Dead WG Document',
    'Active IAB Document',
    'Community Review',
    'Sent to the RFC Editor',
    'Active RG Document',
    'In RG Last Call',
    'Awaiting IRSG Reviews',
    'In IESG Review',
    'Document on Hold Based On IESG Request',
    'Submission Received',
    'In ISE Review',
    'In IESG Review',
    'RFC Published',
    'Dead',
    'IESG Evaluation',
    'Publication Requested',
    'In Last Call',
]
