defaultSemverRangePrefix: ""

enableTelemetry: false

nodeLinker: pnp

packageExtensions:
  "@parcel/cache@*":
    dependencies:
      "@parcel/core": 2.6.2
  "@parcel/fs@*":
    dependencies:
      "@parcel/core": 2.6.2
  "@parcel/optimizer-image@*":
    dependencies:
      "@parcel/core": 2.6.2
  "@parcel/package-manager@*":
    dependencies:
      "@parcel/core": 2.6.2
  "@parcel/workers@*":
    dependencies:
      "@parcel/core": 2.6.2
  eslint-config-standard@*:
    dependencies:
      eslint-plugin-n: "*"
  select2-bootstrap-5-theme@*:
    dependencies:
      "@popperjs/core": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-3.2.2.cjs
