openapi: 3.0.3
info:
    title: Datatracker RPC API
    description: Datatracker RPC API
    version: 1.0.0
servers:
    -   url: 'http://localhost:8000/api/rpc'
paths:
    /person/{personId}:
        get:
            operationId: get_person_by_id
            summary: Find person by ID
            description: Returns a single person
            parameters:
                - name: personId
                  in: path
                  description: ID of person to return
                  required: true
                  schema:
                      type: integer
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Person'
                '404':
                    description: Not found

    /persons/:
        post:
            operationId: get_persons
            summary: Get a batch of persons
            description: returns a dict of person pks to person names
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: array
                            items:
                                type: integer
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                additionalProperties:
                                    type: string

                
    /person/create_demo_person/:
        post:
            operationId: create_demo_person
            summary: Build a datatracker Person for RPC demo purposes
            description: returns a datatracker User id for a person created with the given name
            requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        name:
                          type: string
            responses:
              '200':
                  description: OK
                  content:
                      application/json:
                        schema:
                          type: object
                          properties:
                            user_id:
                              type: integer
                            person_pk:
                              type: integer

    /doc/create_demo_draft/:
        post:
            operationId: create_demo_draft
            summary: Build a datatracker WG draft for RPC demo purposes
            description: returns a datatracker document id for a draft created with the provided name and states. The arguments, if present, are passed directly to the WgDraftFactory
            requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        name:
                          type: string
                        stream_id:
                          type: string
                        rev:
                          type: string
                        states:
                          type: array
                          items:
                            type: array
                            items:
                                type: string
            responses:
              '200':
                  description: OK
                  content:
                      application/json:
                        schema:
                          type: object
                          properties:
                            doc_id:
                              type: integer
                            name:
                              type: string

    /doc/submitted_to_rpc:
        get:
            operationId: submitted_to_rpc
            summary: List documents ready to enter the RFC Editor Queue
            description: List documents ready to enter the RFC Editor Queue
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SubmittedToQueue'
                                
    /doc/drafts/{docId}:
        get:
            operationId: get_draft_by_id
            summary: Get a draft
            description: Returns the draft for the requested ID
            parameters:
                - name: docId
                  in: path
                  description: ID of draft to retrieve
                  required: true
                  schema:
                      type: integer
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Draft'
                '404':
                    description: Not found

    /doc/drafts_by_names/:
        post:
            operationId: get_drafts_by_names
            summary: Get a batch of drafts by draft names
            description: returns a dict of drafts with matching names
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: array
                            items:
                                type: string
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                additionalProperties:
                                    $ref:'#/components/schemas/Draft'

    /doc/rfc/original_stream/:
        get:
            operationId: get_rfc_original_streams
            summary: Get the streams rfcs were originally published into
            description: returns a list of dicts associating an rfc with its originally published stream
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/OriginalStream'   

    /subject/{subjectId}/person:
        get:
            operationId: get_subject_person_by_id
            summary: Find person for OIDC subject by ID
            description: Returns a single person
            parameters:
                -   name: subjectId
                    in: path
                    description: subject ID of person to return
                    required: true
                    schema:
                        type: string
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Person'
                '400':
                    description: No such subject or no person for this subject
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '404':
                    description: No such subject or no person for this subject
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

components: 
    schemas: 
        Person:
            type: object
            properties:
                id:
                    type: integer
                    example: 1234
                plain_name:
                    type: string
                    example: John Doe

        SubmittedToQueue:
            type: object
            properties:
                submitted_to_rpc:
                    type: array
                    items:
                        type: object
                        properties:
                            name: 
                              type: string
                            pk: 
                              type: integer
                            stream: 
                              type: string
                            submitted: 
                                type: string
                                format: date
        
        ErrorResponse:
            type: object
            properties:
                error:
                    type: string
            
        Draft:
            type: object
            properties: 
                id:
                    type: integer
                name:
                    type: string
                rev:
                    type: string
                stream:
                    type: string
                title:
                    type: string
                pages:
                    type: integer
                authors:
                    type: array
                    items:
                        $ref: '#/components/schemas/Person'

        OriginalStream:
            type: object
            properties:
                original_stream:
                    type: list
                    items:
                        properties:
                            rfc_number:
                                type: integer
                            stream:
                                type: string

    securitySchemes: 
        ApiKeyAuth:
            type: apiKey
            in: header
            name: X-API-KEY

security:
    - ApiKeyAuth: []
