# Generated by Django 4.2.2 on 2023-06-12 19:35

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import ietf.utils.models


def forward(apps, schema_editor):
    CommunityList = apps.get_model('community', 'CommunityList')
    for clist in CommunityList.objects.all():
        try:
            clist.person = clist.user.person
        except:
            clist.person = None
        clist.save()

def reverse(apps, schema_editor):
    CommunityList = apps.get_model('community', 'CommunityList')
    for clist in CommunityList.objects.all():
        try:
            clist.user = clist.person.user
        except:
            clist.user = None
        clist.save()

class Migration(migrations.Migration):
    dependencies = [
        ("community", "0002_auto_20230320_1222"),
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitylist",
            name="person",
            field=ietf.utils.models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="person.Person",
            ),
        ),
        migrations.RunPython(forward, reverse),
        migrations.RemoveField(
            model_name="communitylist",
            name="user",
            field=ietf.utils.models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
    ]
