# Generated by Django 2.2.28 on 2022-06-30 23:15


from django.db import migrations


def forward(apps, schema_editor):
    SearchRule = apps.get_model('community', 'SearchRule')
    Group = apps.get_model('group', 'Group')
    State = apps.get_model('doc', 'State')
    for group in Group.objects.filter(type_id__in=['wg','rg'], state_id='active'):
        Rule = SearchRule.objects.filter(group = group)
        if Rule.exists():
            SearchRule.objects.create(community_list=Rule[0].community_list, rule_type="group_exp", group=group, state=State.objects.get(slug="expired", type="draft"),)


def reverse(apps, schema_editor):
    SearchRule = apps.get_model('community', 'SearchRule')
    SearchRule.objects.filter(rule_type='group_exp').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('community', '0008_add_group_exp_rule'),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
