# Generated by Django 2.2.28 on 2022-11-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_add_group_exp_rule_to_groups'),
    ]

    operations = [
        migrations.RunSQL(
            sql="alter table community_communitylist_added_docs modify document_id int unsigned not null;",
            reverse_sql="alter table community_communitylist_added_docs modify document_id varchar(255) not null;"
        ),
                migrations.RunSQL(
            sql="alter table community_searchrule_name_contains_index modify document_id int unsigned not null;",
            reverse_sql="alter table community_searchrule_name_contains_index modify document_id varchar(255) not null;"
        ),
    ]
