# Copyright The IETF Trust 2019-2020, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-10 10:37


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0027_add_irsg_doc_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRSGBallotDocEvent',
            fields=[
                ('ballotdocevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doc.BallotDocEvent')),
                ('duedate', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('doc.ballotdocevent',),
        ),
    ]
