# Generated by Django 4.2.3 on 2023-08-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0015_delete_docalias"),
        ("ipr", "0002_iprdocrel_no_aliases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iprdisclosurebase",
            name="docs",
            field=models.ManyToManyField(through="ipr.IprDocRel", to="doc.document"),
        ),
    ]
