# Generated by Django 4.2.24 on 2025-10-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipr", "0004_holderiprdisclosure_is_blanket_disclosure"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemovedIprDisclosure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("removed_id", models.PositiveBigIntegerField()),
                ("reason", models.TextField()),
            ],
        ),
    ]
