# Generated by Django 2.2.17 on 2020-11-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipr', '0007_create_ipr_doc_events'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='iprdisclosurebase',
            index=models.Index(fields=['-time', '-id'], name='ipr_iprdisc_time_846a78_idx'),
        ),
        migrations.AddIndex(
            model_name='iprevent',
            index=models.Index(fields=['-time', '-id'], name='ipr_ipreven_time_9630c4_idx'),
        ),
    ]
