# Generated by Django 2.2.24 on 2021-10-28 11:20

import os

from django.core.management import call_command
from django.db import migrations


def forwards(apps, schema_editor):
    call_command('generate_draft_recursive_txt')
    os.chmod('/a/ietfdata/derived/ipr_draft_recursive.txt', 0o666)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ipr', '0008_auto_20201109_0439'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
    ]
