# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:01
from __future__ import unicode_literals

from django.db import migrations
from ietf.meeting.utils import create_proceedings_templates

def forward(apps, schema_editor):
    Meeting = apps.get_model('meeting', 'Meeting')
    DBTemplate = apps.get_model('dbtemplate', 'DBTemplate')

    meeting = Meeting.objects.get(number=97)
    template = DBTemplate.objects.get(path='/meeting/proceedings/97/attendees.html')
    template.delete()
    create_proceedings_templates(meeting)

def backward(apps, schema_editor):
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0047_import_shared_audio_files'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
