# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0050_add_room_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='resources',
            field=models.ManyToManyField(blank=True, to='meeting.ResourceAssociation'),
        ),
    ]
