# Copyright The IETF Trust 2019-2020, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-30 09:02


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailtrigger', '0007_add_review_mailtriggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtrigger',
            name='slug',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        # The above migration will not update the ManyToMany tables, which also reference
        # the mailtrigger pk as varchar(32), so manual SQL is used.
        # https://code.djangoproject.com/ticket/25012
        migrations.RunSQL(
            sql='ALTER TABLE `mailtrigger_mailtrigger_to` MODIFY `mailtrigger_id` varchar(64);',
            reverse_sql='ALTER TABLE `mailtrigger_mailtrigger_to` MODIFY `mailtrigger_id` varchar(32);',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE `mailtrigger_mailtrigger_cc` MODIFY `mailtrigger_id` varchar(64);',
            reverse_sql='ALTER TABLE `mailtrigger_mailtrigger_cc` MODIFY `mailtrigger_id` varchar(32);',
        ),
    ]
