# Generated by Django 2.2.28 on 2023-03-07 16:54

from django.db import migrations


def forward(apps, schema_editor):
    Session = apps.get_model('meeting', 'Session')
    Meeting = apps.get_model('meeting', 'Meeting')
    Room = apps.get_model('meeting', 'Room')
    full_meetings = Meeting.objects.filter(type_id='ietf', schedule__isnull=False)
    schedules = {m.schedule for m in full_meetings} | {m.schedule.base for m in full_meetings if m.schedule.base}
    rooms_with_meetecho = Room.objects.filter(urlresource__name_id__in=['meetecho', 'meetecho_onsite']).distinct()
    sessions_with_meetecho = Session.objects.filter(
        timeslotassignments__schedule__in=schedules,
        timeslotassignments__timeslot__location__in=rooms_with_meetecho,
    ).distinct()
    sessions_with_meetecho.update(has_onsite_tool=True)


def reverse(apps, schema_editor):
    Session = apps.get_model('meeting', 'Session')
    Session.objects.all().update(has_onsite_tool=False)


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_session_has_onsite_tool'),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
