# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_rename_modified_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='attendees',
            field=models.IntegerField(blank=True, default=0, help_text='Number of Attendees for backfilled meetings, leave it to 0 for new meetings, and then it is calculated from the registrations'),
        ),
    ]
