# Copyright The IETF Trust 2018-2020, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 09:17


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_rename_modified_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='attendees',
            field=models.IntegerField(blank=True, default=None, help_text='Number of Attendees for backfilled meetings, leave it blank for new meetings, and then it is calculated from the registrations', null=True),
        ),
    ]
