# Generated by Django 4.2.7 on 2023-11-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meeting", "0004_session_chat_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="acknowledgements",
            field=models.TextField(
                blank=True,
                help_text="Acknowledgements for use in meeting proceedings.  Use Markdown.",
            ),
        ),
    ]
