# Generated by Django 4.2.9 on 2024-01-12 18:34

from django.db import migrations
import django.db.models.deletion
import ietf.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0021_narrativeminutes"),
        ("meeting", "0005_alter_sessionpresentation_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionpresentation",
            name="document",
            field=ietf.utils.models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presentations",
                to="doc.document",
            ),
        ),
    ]
