# Generated by Django 4.2.15 on 2024-08-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0007_attended_origin_attended_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedtimesessassignment",
            name="notes",
        ),
    ]
