# Copyright The IETF Trust 2018-2020, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 14:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_rename_meeting_agenda_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='agenda_info_note',
            field=models.TextField(blank=True, help_text='Text in this field will be placed at the top of the html agenda page for the meeting.  HTML can be used, but will not be validated.'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='agenda_warning_note',
            field=models.TextField(blank=True, help_text='Text in this field will be placed more prominently at the top of the html agenda page for the meeting.  HTML can be used, but will not be validated.'),
        ),
    ]
