# Copyright The IETF Trust 2018-2020, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 14:23


from django.db import migrations

def forward(apps,schema_editor):
    Meeting = apps.get_model('meeting','Meeting')
    Meeting.objects.filter(number=103).update(agenda_info_note=
      'To see the list of unofficial side meetings, or to reserve meeting '
      'space, please see the '
      '<a href="https://trac.ietf.org/trac/ietf/meeting/wiki/103sidemeetings">'
      'meeting wiki</a>.'
    )

def reverse(apps,schema_editor):
    Meeting = apps.get_model('meeting','Meeting')
    Meeting.objects.filter(number=103).update(agenda_info_note="")

class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_add_agenda_info_note'),
        ('person', '0008_auto_20181014_1448'),
    ]

    operations = [
        migrations.RunPython(forward,reverse),
    ]
