# Generated by Django 4.2.20 on 2025-03-13 08:06

from django.db import migrations
import django.db.models.deletion
import ietf.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("name", "0016_populate_new_reg_names"),
        ("person", "0004_alter_person_photo_alter_person_photo_thumb"),
        ("meeting", "0011_registration_registrationticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="person",
            field=ietf.utils.models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="person.person",
            ),
        ),
        migrations.AlterField(
            model_name="registrationticket",
            name="attendance_type",
            field=ietf.utils.models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="name.attendancetypename",
            ),
        ),
        migrations.AlterField(
            model_name="registrationticket",
            name="ticket_type",
            field=ietf.utils.models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="name.registrationtickettypename",
            ),
        ),
    ]
