# Generated by Django 4.2.20 on 2025-03-13 08:55

from django.db import migrations


def forward(apps, schema_editor):
    AttendanceTypeName = apps.get_model('name', 'AttendanceTypeName')
    RegistrationTicketTypeName = apps.get_model('name', 'RegistrationTicketTypeName')
    AttendanceTypeName.objects.create(
        name='Unknown',
        slug='unknown')
    RegistrationTicketTypeName.objects.create(
        name='Unknown',
        slug='unknown')


def reverse(apps, schema_editor):
    AttendanceTypeName = apps.get_model('name', 'AttendanceTypeName')
    RegistrationTicketTypeName = apps.get_model('name', 'RegistrationTicketTypeName')
    AttendanceTypeName.objects.get(slug='unknown').delete()
    RegistrationTicketTypeName.objects.get(slug='unknown').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0012_alter_registration_person_and_more"),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
