# Copyright The IETF Trust 2019-2020, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-21 14:03


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0018_document_primary_key_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidesubmission',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
