# Copyright The IETF Trust 2019-2020, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-18 04:01


from django.db import migrations
import django.db.models.deletion
import ietf.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0020_remove_future_break_sessions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='agenda',
            new_name='schedule',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='meeting',
            field=ietf.utils.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_set', to='meeting.Meeting'),
        ),
    ]
