# Generated by Django 2.2.14 on 2020-07-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0029_businessconstraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='joint_with_groups',
            field=models.ManyToManyField(blank=True, related_name='sessions_joint_in', to='group.Group'),
        ),
    ]
