# Generated by Django 2.2.14 on 2020-08-03 11:53

from django.db import migrations
import django.db.models.deletion
import ietf.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0018_slidesubmissionstatusname'),
        ('doc', '0035_populate_docextresources'),
        ('meeting', '0030_allow_empty_joint_with_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidesubmission',
            name='doc',
            field=ietf.utils.models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doc.Document'),
        ),
    ]
