# Generated by Django 2.2.14 on 2020-08-03 11:53

from django.db import migrations
import django.db.models.deletion
import ietf.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0031_auto_20200803_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidesubmission',
            name='status',
            field=ietf.utils.models.ForeignKey(null=True, default='pending', on_delete=django.db.models.deletion.SET_NULL, to='name.SlideSubmissionStatusName'),
        ),
    ]
