# Generated by Django 2.0.13 on 2020-08-04 06:22

from django.db import migrations
import django.db.models.deletion
import ietf.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0034_schedule_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='origin',
            field=ietf.utils.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.Schedule'),
        ),
    ]
