# Generated by Django 2.2.16 on 2020-09-08 03:34

from django.db import migrations
import django.db.models.deletion
import ietf.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0036_add_schedule_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='base',
            field=ietf.utils.models.ForeignKey(blank=True, help_text='Sessions scheduled in the base schedule show up in this schedule too.', limit_choices_to={'base': None}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivedschedule_set', to='meeting.Schedule'),
        ),
    ]
