# Generated by Django 2.2.16 on 2020-10-05 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0037_auto_20200908_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(help_text='Letters, numbers and -:_ allowed.', max_length=64, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-:_]*$')]),
        ),
    ]
