# Generated by Django 2.2.17 on 2020-11-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0038_auto_20201005_1123'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['-date', '-id'], name='meeting_mee_date_40ca21_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['-time', '-id'], name='meeting_tim_time_b802cb_idx'),
        ),
    ]
