# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 11:59
from __future__ import unicode_literals

import os

from django.db import migrations
from ietf.secr.proceedings.proc_utils import import_audio_files


def purge_missing_files(apps, meeting):
    Document = apps.get_model('doc', 'Document')
    url = 'https://www.ietf.org/audio/ietf{}'.format(meeting.number)
    documents = Document.objects.filter(external_url__startswith=url)
    for document in documents:
        filename = document.external_url.split('/')[-1]
        if not os.path.exists(os.path.join('/a/www/audio/ietf{}'.format(meeting.number),filename)):
            print "Removing missing recording: {} ({})".format(filename,document.pk)
            document.delete()

def forward(apps, schema_editor):
    Meeting = apps.get_model('meeting', 'Meeting')
    Document = apps.get_model('doc', 'Document')
    for meeting in Meeting.objects.filter(number__in=range(94,98)):
        print '\nMeeting #{}:'.format(meeting.number)
        purge_missing_files(apps, meeting)
        before = Document.objects.filter(type='recording').count()
        import_audio_files(meeting)
        after = Document.objects.filter(type='recording').count()
        print '    {} Documents Added'.format(after - before)

def backward(apps, schema_editor):
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0046_auto_20170201_0857'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
