# Generated by Django 2.2.24 on 2021-10-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0048_session_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='on_agenda',
            field=models.BooleanField(default=True, help_text='Is this session visible on the meeting agenda?'),
        ),
    ]
