# Copyright The IETF Trust 2022, All Rights Reserved
# Generated by Django 2.2.28 on 2022-06-17 08:40

from django.db import migrations, models
import django.db.models.deletion
import ietf.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0023_auto_20220615_1006'),
        ('meeting', '0052_auto_20220503_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', ietf.utils.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
                ('session', ietf.utils.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Session')),
            ],
            options={
                'unique_together': {('person', 'session')},
            },
        ),
    ]
