# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 06:14
from __future__ import unicode_literals

from django.db import migrations

import datetime

def forward(apps,schema_editor):
    Meeting = apps.get_model('meeting','Meeting')
    ImportantDate = apps.get_model('meeting', 'ImportantDate')
    ImportantDateName = apps.get_model('name', 'ImportantDateName')

    for num in [98,99]:
        meeting = Meeting.objects.get(number=num)
        for datename in ImportantDateName.objects.filter(used=True):
            ImportantDate.objects.create(meeting=meeting,name=datename,date=meeting.date+datetime.timedelta(days=datename.default_offset_days-1))

    ImportantDate.objects.filter(meeting__number=99,name__slug='openreg').update(date='2017-03-27')

    ImportantDate.objects.filter(meeting__number=98,name__slug='openreg').update(date='2016-11-28')
    ImportantDate.objects.filter(meeting__number=98,name__slug='opensched').update(date='2016-12-19')

def reverse(apps,schema_editor):
    ImportantDate = apps.get_model('meeting', 'ImportantDate')
    ImportantDate.objects.filter(meeting__number__in=[99,98]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0053_important_date'),
        ('name', '0026_popuulate-important-date-names'),
    ]

    operations = [
        migrations.RunPython(forward,reverse),
    ]
