# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-25 03:17
from __future__ import unicode_literals

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0056_fix-slide-name-slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='days',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1)],
                help_text=b'The number of days the meeting lasts'),
        ),
    ]
