# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-25 03:22
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Meeting = apps.get_model('meeting', 'Meeting')
    for m in Meeting.objects.all():
        if m.type_id == 'ietf':
            if m.number.isdigit() and int(m.number) >= 100:
                m.days = 7
            else:
                m.days = 6
        else:
            m.days = 1
        m.save()

def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0057_meeting_days'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
