# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-06 08:26
from __future__ import unicode_literals

import datetime

from django.db import migrations, models

def forwards(apps, schema_editor):
    Meeting = apps.get_model('meeting', 'Meeting')
    stop_date = datetime.date.today() + datetime.timedelta(days=30)
    for m in Meeting.objects.filter(show_important_dates=False):
        if m.date < stop_date:
            m.show_important_dates = True
            m.save()

def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0058_set_new_field_meeting_days_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='show_important_dates',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forwards, backwards),
    ]
