# Generated by Django 2.2.28 on 2023-02-08 22:41

from django.db import migrations
from django.db.models import Subquery, OuterRef, Value, TextField
from django.db.models.functions import Coalesce


def forward(apps, schema_editor):
    Session = apps.get_model('meeting', 'Session')
    SchedulingEvent = apps.get_model('meeting', 'SchedulingEvent')
    Person = apps.get_model('person', 'Person')

    # annotation borrowed from SessionQuerySet.with_current_status()
    sessions = Session.objects.annotate(
        # coalesce with '' to avoid nulls which give funny
        # results, e.g. .exclude(current_status='canceled') also
        # skips rows with null in them
        current_status=Coalesce(
            Subquery(
                SchedulingEvent.objects.filter(
                    session=OuterRef('pk')
                ).order_by(
                    '-time', '-id'
                ).values('status')[:1]),
            Value(''),
            output_field=TextField()),
    ).exclude(
        current_status__in=['canceled', 'canceledpa'],
    )
    system_person = Person.objects.get(name='(System)')

    # Cancel any uncanceled sessions marked as 'CANCELED' in the agenda_note
    for session in sessions.filter(agenda_note='CANCELED'):
        SchedulingEvent.objects.create(session=session, status_id='canceled', by=system_person)


def reverse(apps, schema_editor):
    pass  # nothing to be done


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0059_rename_sessions'),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
