# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-22 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0059_meeting_show_important_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='short',
            field=models.CharField(default=b'', max_length=3),
        ),
    ]
