# Generated by Django 2.2.28 on 2022-11-10 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0060_normalize_canceled_sessions'),
        ('utils', '0004_pause_to_change_database_engines'),
    ]

    operations = [
        # reversesql is intentionally not provided. There is no looking back...
        migrations.RunSQL(sql="update meeting_meeting set idsubmit_cutoff_time_utc=idsubmit_cutoff_time_utc/1000"),
        migrations.RunSQL(sql="alter table meeting_meeting alter column idsubmit_cutoff_time_utc type interval using (idsubmit_cutoff_time_utc::text||' milliseconds')::interval;"),
        migrations.RunSQL(sql="update meeting_meeting set idsubmit_cutoff_warning_days=idsubmit_cutoff_warning_days/1000"),
        migrations.RunSQL(sql="alter table meeting_meeting alter column idsubmit_cutoff_warning_days type interval using (idsubmit_cutoff_warning_days::text||' milliseconds')::interval;"),
        migrations.RunSQL(sql="update meeting_timeslot set duration=duration/1000"),
        migrations.RunSQL(sql="alter table meeting_timeslot alter column duration type interval using (duration::text||' milliseconds')::interval;"),
        migrations.RunSQL(sql="update meeting_session set requested_duration=requested_duration/1000"),
        migrations.RunSQL(sql="alter table meeting_session alter column requested_duration type interval using (requested_duration::text||' milliseconds')::interval;"),      
    ]
