# Generated by Django 4.2.2 on 2023-06-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomcom", "0002_add_uncheck_reminder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomination",
            name="share_nominator",
            field=models.BooleanField(
                default=False,
                help_text="Check this box to allow the NomCom to let the person you are nominating know that you were one of the people who nominated them. If you do not check this box, your name will be confidential and known only within NomCom.",
                verbose_name="OK to share nominator's name with candidate",
            ),
        ),
    ]
