# Generated by Django 4.2.7 on 2023-11-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomcom", "0003_alter_nomination_share_nominator"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="origin",
            field=models.CharField(default="datatracker", max_length=32),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="time",
            field=models.DateTimeField(auto_now_add=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="withdrawn",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
