# Generated by Django 4.2.2 on 2023-06-14 19:47

from django.db import migrations
import django.db.models.deletion
import ietf.utils.models


def forward(apps, schema_editor):
    Nomination = apps.get_model('nomcom', 'Nomination')
    for nomination in Nomination.objects.all():
        try:
            nomination.person = nomination.user.person
        except:
            nomination.person = None
        nomination.save()

    Feedback = apps.get_model('nomcom', 'Feedback')
    for feedback in Feedback.objects.all():
        try:
            feedback.person = feedback.user.person
        except:
            feedback.person = None
        feedback.save()

def reverse(apps, schema_editor):
    Nomination = apps.get_model('nomcom', 'Nomination')
    for nomination in Nomination.objects.all():
        try:
            nomination.user = nomination.person.user
        except:
            nomination.user = None
        nomination.save()

    Feedback = apps.get_model('nomcom', 'Feedback')
    for feedback in Feedback.objects.all():
        try:
            feedback.user = feedback.person.user
        except:
            feedback.user = None
        feedback.save()

class Migration(migrations.Migration):
    dependencies = [
        ("person", "0001_initial"),
        ("nomcom", "0003_alter_nomination_share_nominator"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="person",
            field=ietf.utils.models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="person.person",
            ),
        ),
        migrations.AddField(
            model_name="nomination",
            name="person",
            field=ietf.utils.models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="person.person",
            ),
        ),
        migrations.RunPython(forward, reverse),
        migrations.RemoveField(
            model_name="feedback",
            name="user",
            field=ietf.utils.models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.user",
            ),
        ),
        migrations.RemoveField(
            model_name="nomination",
            name="user",
            field=ietf.utils.models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.user",
            ),
        ),
    ]
