# Generated by Django 4.2.7 on 2023-11-05 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomcom", "0003_alter_nomination_share_nominator"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="origin",
            field=models.CharField(default="datatracker", max_length=32),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="withdrawn",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 5, 0, 0, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
