# Generated by Django 2.2.16 on 2020-10-08 05:06

from django.db import migrations
import django.db.models.deletion
import ietf.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('nomcom', '0007_position_is_iesg_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='audience',
            field=ietf.utils.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='name.TopicAudienceName', verbose_name='Who can provide feedback (intended audience)'),
        ),
    ]
