# Generated by Django 2.2.17 on 2020-11-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomcom', '0008_auto_20201008_0506'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['time'], name='nomcom_feed_time_35cf38_idx'),
        ),
    ]
