# Generated by Django 2.2.28 on 2022-07-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomcom', '0012_populate_volunteers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomcom',
            name='is_accepting_volunteers',
            field=models.BooleanField(default=False, help_text='Is this nomcom currently accepting volunteers?', verbose_name='Accepting volunteers'),
        ),
    ]
