# Copyright The IETF Trust 2019-2020, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-03 12:34


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_allow_notify_ad_when_to_be_blank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrequest',
            name='old_id',
        ),
    ]
