# Copyright The IETF Trust 2019-2020, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-01 04:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_add_remind_days_open_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewteamsettings',
            name='remind_days_unconfirmed_assignments',
            field=models.PositiveIntegerField(blank=True, help_text="To send a periodic email reminder to reviewers of review assignments that are not accepted yet, enter the number of days between these reminders. Clear the field if you don't want these reminders to be sent.", null=True, verbose_name='Periodic reminder of not yet accepted or rejected review assignments to reviewer every X days'),
        ),

    ]
