# Copyright The IETF Trust 2019-2020, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-15 10:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0017_add_review_team_remind_days_unconfirmed_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreviewersettings',
            name='remind_days_before_deadline',
            field=models.IntegerField(blank=True, help_text="To get an email reminder in case you forget to do an assigned review, enter the number of days before review deadline you want to receive it. Clear the field if you don't want this reminder.", null=True),
        ),
        migrations.AlterField(
            model_name='historicalreviewersettings',
            name='remind_days_open_reviews',
            field=models.PositiveIntegerField(blank=True, help_text="To get a periodic email reminder of all your open reviews, enter the number of days between these reminders. Clear the field if you don't want these reminders.", null=True, verbose_name='Periodic reminder of open reviews every X days'),
        ),
        migrations.AlterField(
            model_name='reviewersettings',
            name='remind_days_before_deadline',
            field=models.IntegerField(blank=True, help_text="To get an email reminder in case you forget to do an assigned review, enter the number of days before review deadline you want to receive it. Clear the field if you don't want this reminder.", null=True),
        ),
        migrations.AlterField(
            model_name='reviewteamsettings',
            name='remind_days_unconfirmed_assignments',
            field=models.PositiveIntegerField(blank=True, help_text="To send a periodic email reminder to reviewers of review assignments they have neither accepted nor rejected, enter the number of days between these reminders. Clear the field if you don't want these reminders to be sent.", null=True, verbose_name='Periodic reminder of not yet accepted or rejected review assignments to reviewer every X days'),
        ),
    ]
