# Copyright The IETF Trust 2019, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-18 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0008_reviewerqueuepolicyname'),
        ('review', '0020_auto_20191115_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewteamsettings',
            name='reviewer_queue_policy',
            field=models.ForeignKey(default='RotateAlphabetically', on_delete=django.db.models.deletion.PROTECT, to='name.ReviewerQueuePolicyName'),
        ),
        migrations.AddField(
            model_name='historicalreviewersettings',
            name='request_assignment_next',
            field=models.BooleanField(default=False,
                                      help_text='If you would like to be assigned to a review as soon as possible, select this option. It is automatically reset once you receive any assignment.',
                                      verbose_name='Select me next for an assignment'),
        ),
        migrations.AddField(
            model_name='reviewersettings',
            name='request_assignment_next',
            field=models.BooleanField(default=False,
                                      help_text='If you would like to be assigned to a review as soon as possible, select this option. It is automatically reset once you receive any assignment.',
                                      verbose_name='Select me next for an assignment'),
        ),
    ]
