# -*- coding: utf-8 -*-
# Copyright The IETF Trust 2020, All Rights Reserved
# Generated by Django 1.11.26 on 2019-12-21 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0022_reviewer_queue_policy_and_request_assignment_next'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreviewersettings',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
