# Generated by Django 2.2.28 on 2022-05-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0027_unique_constraint_for_reviewersettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalreviewassignment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical review assignment', 'verbose_name_plural': 'historical review assignments'},
        ),
        migrations.AlterModelOptions(
            name='historicalreviewersettings',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical reviewer settings', 'verbose_name_plural': 'historical reviewer settings'},
        ),
        migrations.AlterModelOptions(
            name='historicalreviewrequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical review request', 'verbose_name_plural': 'historical review requests'},
        ),
        migrations.AlterModelOptions(
            name='historicalunavailableperiod',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical unavailable period', 'verbose_name_plural': 'historical unavailable periods'},
        ),
        migrations.AlterField(
            model_name='historicalreviewassignment',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalreviewersettings',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalreviewrequest',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalunavailableperiod',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
