# Generated by Django 2.2.28 on 2022-07-12 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0028_auto_20220513_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreviewrequest',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reviewrequest',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reviewwish',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
