# Generated by Django 2.2.28 on 2022-10-18 15:43

from django.db import migrations, models
import ietf.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0029_use_timezone_now_for_review_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalunavailableperiod',
            name='start_date',
            field=models.DateField(default=ietf.utils.timezone.date_today, help_text="Choose the start date so that you can still do a review if it's assigned just before the start date - this usually means you should mark yourself unavailable for assignment some time before you are actually away. The default is today.", null=True),
        ),
        migrations.AlterField(
            model_name='unavailableperiod',
            name='start_date',
            field=models.DateField(default=ietf.utils.timezone.date_today, help_text="Choose the start date so that you can still do a review if it's assigned just before the start date - this usually means you should mark yourself unavailable for assignment some time before you are actually away. The default is today.", null=True),
        ),
    ]
