# Generated by Django 4.2.5 on 2023-09-28 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0007_alter_docevent_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dochistory",
            name="note",
        ),
        migrations.RemoveField(
            model_name="document",
            name="note",
        ),
    ]
