# Generated by Django 4.2.2 on 2023-06-20 18:36

from django.db import migrations


def forward(apps, schema_editor):
    """Point "rfc..." DocAliases at the rfc-type Document"""
    DocAlias = apps.get_model("doc", "DocAlias")
    Document = apps.get_model("doc", "Document")
    for rfc_alias in DocAlias.objects.filter(name__startswith="rfc"):
        rfc = Document.objects.get(name=rfc_alias.name)
        rfc_alias.docs.set([rfc])


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0008_move_rfc_docevents"),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
