# Generated by Django 4.2.2 on 2023-06-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc", "0009_add_rfc_states"),
    ]

    operations = [
        migrations.AddField(
            model_name="dochistory",
            name="rfc_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="rfc_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
