# Copyright The IETF Trust 2019, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 13:02


from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0009_move_non_url_externalurls_to_uploaded_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenturl',
            name='url',
            field=models.URLField(max_length=2083),
        ),
    ]
