# Generated by Django 4.2.14 on 2024-07-25 22:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ietf.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0021_narrativeminutes"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnprocessableDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rev", models.CharField(max_length=16, verbose_name="revision")),
                (
                    "proc_type",
                    models.CharField(
                        choices=[("pdfize", "Pdfize")],
                        help_text="type of processing that fails for this document",
                        max_length=16,
                    ),
                ),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "document",
                    ietf.utils.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doc.document"
                    ),
                ),
            ],
        ),
    ]
