# Generated by Django 4.2.15 on 2024-08-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0021_narrativeminutes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dochistory",
            name="internal_comments",
        ),
        migrations.RemoveField(
            model_name="document",
            name="internal_comments",
        ),
    ]
