# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0023_set_docevent_rev_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newrevisiondocevent',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='submissiondocevent',
            name='revision',
        ),
    ]
