# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0024_del_docevent_subclass_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docevent',
            name='rev',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name=b'revision'),
        ),
    ]
