# Generated by Django 4.2.21 on 2025-05-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doc", "0026_storedobject_committed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storedobject",
            old_name="committed",
            new_name="replicated",
        ),
    ]
