# Generated by Django 2.1.15 on 2020-06-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0031_set_state_for_charters_of_replaced_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballotpositiondocevent',
            name='send_email',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='consensusdocevent',
            name='consensus',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
