# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-14 13:18
from __future__ import unicode_literals

from django.db import migrations

changes = [
  [ 'conflict-review-irtf-samrg-common-api',                '02', '2013-10-04 10:38:54', '2013-10-04 10:38:52' ],
  [ 'conflict-review-irtf-dtnrg-dgram-clayer',              '02', '2013-08-25 08:46:03', '2013-08-25 08:45:53' ],
  [ 'conflict-review-irtf-dtnrg-dgram-clayer',              '01', '2013-08-24 12:25:14', '2013-08-24 12:25:13' ],
  [ 'conflict-review-hausenblas-csv-fragment',              '02', '2013-10-10 10:17:53', '2013-10-10 10:17:52' ],
  [ 'conflict-review-hoffine-already-dotless',              '04', '2013-10-10 15:53:14', '2013-10-10 15:53:13' ],
  [ 'conflict-review-irtf-sdnrg-layer-terminology',         '01', '2014-10-11 06:51:30', '2014-10-11 06:51:29' ],
  [ 'conflict-review-gont-dhcpv6-stable-privacy-addresses', '01', '2016-05-18 17:51:58', '2016-05-18 17:51:55' ],
]

def forward(apps, schema_editor):
    DocHistory = apps.get_model('doc','DocHistory')
    for name, rev, old, new in changes:
        DocHistory.objects.filter(name=name,rev=rev,time=old).update(time=new)
        

def reverse(apps, schema_editor):
    DocHistory = apps.get_model('doc','DocHistory')
    for name, rev, old, new in changes:
        DocHistory.objects.filter(name=name,rev=rev,time=new).update(time=old)


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0032_auto_20170731_0508'),
    ]

    operations = [
        migrations.RunPython(forward,reverse)
    ]
