# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-26 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0027_docurltagname'),
        ('doc', '0033_fix_conflict_review_dochistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, default=b'', max_length=255)),
                ('url', models.URLField()),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.Document')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='name.DocUrlTagName')),
            ],
        ),
    ]
