# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-29 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0034_documenturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenturl',
            name='url',
            field=models.URLField(max_length=512),
        ),
    ]
