# Generated by Django 2.2.17 on 2020-11-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0037_clean_up_missing_docaliases'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='docevent',
            index=models.Index(fields=['-time', '-id'], name='doc_doceven_time_1a258f_idx'),
        ),
    ]
