# Generated by Django 2.2.17 on 2020-11-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0038_auto_20201109_0429'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dochistoryauthor',
            index=models.Index(fields=['document', 'order'], name='doc_dochist_documen_7e2441_idx'),
        ),
        migrations.AddIndex(
            model_name='documentauthor',
            index=models.Index(fields=['document', 'order'], name='doc_documen_documen_7fabe2_idx'),
        ),
    ]
