# Generated by Django 2.2.17 on 2021-01-15 12:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
import ietf.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0018_auto_20201109_0439'),
        ('doc', '0040_add_changed_action_holders_docevent_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentActionHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(default=datetime.datetime.now)),
                ('document', ietf.utils.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.Document')),
                ('person', ietf.utils.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='action_holders',
            field=models.ManyToManyField(blank=True, through='doc.DocumentActionHolder', to='person.Person'),
        ),
        migrations.AddConstraint(
            model_name='documentactionholder',
            constraint=models.UniqueConstraint(fields=('document', 'person'), name='unique_action_holder'),
        ),
    ]
