# Generated by Django 2.2.23 on 2021-05-25 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0018_auto_20201109_0439'),
        ('doc', '0042_bofreq_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='BofreqEditorDocEvent',
            fields=[
                ('docevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doc.DocEvent')),
                ('editors', models.ManyToManyField(blank=True, to='person.Person')),
            ],
            bases=('doc.docevent',),
        ),
    ]
