# Generated by Django 2.2.28 on 2022-12-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0047_tzaware_deletedevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dochistory',
            name='notify',
            field=models.TextField(blank=True, max_length=1023),
        ),
        migrations.AlterField(
            model_name='document',
            name='notify',
            field=models.TextField(blank=True, max_length=1023),
        ),
    ]
