# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import email.utils


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_message_msgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msgid',
            field=models.CharField(blank=True, default=email.utils.make_msgid, max_length=255, null=True),
        ),
    ]
