# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_auto_20170301_0332'),
        ('name', '0024_merge_20170606_1320'),
        ('message', '0004_change_msgid_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='name.RoleName')),
            ],
        ),
    ]
