# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_add_announcement_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcementfrom',
            options={'verbose_name_plural': 'Announcement From addresses'},
        ),
    ]
