# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_auto_20170731_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementfrom',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
