# Generated by Django 2.2.17 on 2020-11-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_fix_content_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['time'], name='message_mes_time_20eabf_idx'),
        ),
        migrations.AddIndex(
            model_name='sendqueue',
            index=models.Index(fields=['time'], name='message_sen_time_07ab31_idx'),
        ),
    ]
