# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_add_review_doc_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewersettings',
            name='expertise',
            field=models.TextField(blank=True, default=b'', help_text=b"Describe the reviewer's expertise in this team's area", max_length=2048, verbose_name=b"Reviewer's expertise in this team's area"),
        ),
    ]
