#!/usr/bin/env python
# Copyright The IETF Trust 2017, All Rights Reserved

# This is mainly a development helper; regular installation through setup.py
# or pip will create a OS-specific script on the path, which will invoke the
# id2xml.run() function in a similar manner.

import id2xml

id2xml.run()