#!/bin/bash

export DEBIAN_FRONTEND=noninteractive
sudo su - -c "apt-get update \
	&& apt-get install -qy \
                apt-file \
                apt-show-versions \
                graphviz \
                ghostscript \
                apache2-utils \
                chromium-driver \
                enscript \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*"
