#!/bin/bash

export DEBIAN_FRONTEND=noninteractive
sudo su - -c "apt-get update \
	&& apt-get install -qy graphviz ghostscript apache2-utils chromium-driver \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*"
