from django.conf.urls import url
from django.views.generic import RedirectView
from ietf.group import views, views_review

urlpatterns = [
    url(r'^$', 'ietf.group.views.group_home', None, "group_home"),
    url(r'^documents/txt/$', 'ietf.group.views.group_documents_txt'),
    url(r'^documents/$', 'ietf.group.views.group_documents', None, "group_docs"),
    url(r'^documents/manage/$', 'ietf.community.views.manage_list'),
    url(r'^documents/csv/$', 'ietf.community.views.export_to_csv'),
    url(r'^documents/feed/$', 'ietf.community.views.feed'),
    url(r'^documents/subscription/$', 'ietf.community.views.subscription'),
    url(r'^charter/$', 'ietf.group.views.group_about', None, 'group_charter'),
    url(r'^about/$', 'ietf.group.views.group_about', None, 'group_about'),
    url(r'^about/status/$', 'ietf.group.views.group_about_status'),
    url(r'^about/status/edit/$', 'ietf.group.views.group_about_status_edit'),
    url(r'^about/status/meeting/(?P<num>\d+)/$', 'ietf.group.views.group_about_status_meeting'),
    url(r'^history/$','ietf.group.views.history'),
    url(r'^email/$', 'ietf.group.views.email'),
    url(r'^deps/(?P<output_type>[\w-]+)/$', 'ietf.group.views.dependencies'),
    url(r'^meetings/$', 'ietf.group.views.meetings'),
    url(r'^edit/$', 'ietf.group.views_edit.edit', {'action': "edit"}, "group_edit"),
    url(r'^conclude/$', 'ietf.group.views_edit.conclude'),
    url(r'^milestones/$', 'ietf.group.milestones.edit_milestones', {'milestone_set': "current"}, "group_edit_milestones"),
    url(r'^milestones/charter/$', 'ietf.group.milestones.edit_milestones', {'milestone_set': "charter"}, "group_edit_charter_milestones"),
    url(r'^milestones/charter/reset/$', 'ietf.group.milestones.reset_charter_milestones', None, "group_reset_charter_milestones"),
    url(r'^workflow/$', 'ietf.group.views_edit.customize_workflow'),
    url(r'^materials/$', 'ietf.group.views.materials', None, "group_materials"),
    url(r'^materials/new/$', 'ietf.doc.views_material.choose_material_type'),
    url(r'^materials/new/(?P<doc_type>[\w-]+)/$', 'ietf.doc.views_material.edit_material', { 'action': "new" }, "group_new_material"),
    url(r'^archives/$', 'ietf.group.views.derived_archives'),
    url(r'^photos/$', views.group_photos),
    url(r'^reviews/$', views_review.review_requests),
    url(r'^reviews/manage/(?P<assignment_status>assigned|unassigned)/$', views_review.manage_review_requests),
    url(r'^reviews/email-assignments/$', views_review.email_open_review_assignments),
    url(r'^reviewers/$', views_review.reviewer_overview),
    url(r'^reviewers/(?P<reviewer_email>[\w%+-.@]+)/settings/$', views_review.change_reviewer_settings),
    url(r'^secretarysettings/$', views_review.change_review_secretary_settings),
    url(r'^email-aliases/$', RedirectView.as_view(pattern_name='ietf.group.views.email',permanent=False),name='old_group_email_aliases'),
]
