# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomcom', '0014_alter_is_open_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomcom',
            name='show_nominee_pictures',
            field=models.BooleanField(default=True, help_text=b'Display pictures of each nominee (if available) on the feedback pages', verbose_name=b'Show nominee pictures'),
        ),
    ]
