# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumpinfo',
            name='tz',
            field=models.CharField(default=b'UTC', max_length=32),
        ),
    ]
