# Copyright The IETF Trust 2018-2020, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 11:12


from django.db import migrations

def forward(apps, schema_editor):
    NomCom = apps.get_model('nomcom','NomCom')
    NomCom.objects.update(show_accepted_nominees=False)

def reverse(apps, schema_editor):
    pass
    
class Migration(migrations.Migration):

    dependencies = [
        ('nomcom', '0003_nomcom_show_accepted_nominees'),
    ]

    operations = [
        migrations.RunPython(forward,reverse)
    ]

