# Generated by Django 2.2.28 on 2023-03-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterimMeeting',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('meeting.meeting',),
        ),
    ]
