# Copyright The IETF Trust 2018-2020, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 10:52


from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterimMeeting',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('meeting.meeting',),
        ),
    ]
