# Generated by Django 2.2.15 on 2020-08-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proceedings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
