# Generated by Django 4.2.23 on 2025-08-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="xml_version",
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
