# Copyright The IETF Trust 2019-2020, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 06:46


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0019_rename_field_document2'),
        ('submit', '0003_remove_old_document_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='draft2',
            new_name='draft',
        ),
    ]
