# Generated by Django 2.1.15 on 2020-06-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0004_rename_field_document2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissioncheck',
            name='passed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
