# Generated by Django 2.2.15 on 2020-08-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0005_auto_20200624_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='xml_version',
            field=models.CharField(default=None, max_length=4, null=True),
        ),
    ]
