# Generated by Django 2.2.17 on 2020-11-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0006_submission_xml_version'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submissionevent',
            index=models.Index(fields=['-time', '-id'], name='submit_subm_time_fcd790_idx'),
        ),
    ]
