# Generated by Django 2.2.17 on 2021-01-27 12:23

from django.db import migrations, models
import django.db.models.deletion
import ietf.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0020_add_rescheduled_session_name'),
        ('submit', '0007_auto_20201109_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionExtResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('value', models.CharField(max_length=2083)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='name.ExtResourceName')),
                ('submission', ietf.utils.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_resources', to='submit.Submission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
