# Generated by Django 2.2.28 on 2022-07-12 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0008_submissionextresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preapproval',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submissioncheck',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submissionevent',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
