# Generated by Django 2.2.28 on 2022-10-18 15:43

from django.db import migrations, models
import ietf.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0011_use_timezone_now_for_submit_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_date',
            field=models.DateField(default=ietf.utils.timezone.date_today),
        ),
    ]
