# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-29 10:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0020_authors_as_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissioncheck',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
