# Generated by Django 2.2.17 on 2020-11-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liaisons', '0006_document_primary_key_cleanup'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='liaisonstatementevent',
            index=models.Index(fields=['-time', '-id'], name='liaisons_li_time_3e1646_idx'),
        ),
    ]
