# -*- coding: utf-8 -*-
from south.v2 import DataMigration


class Migration(DataMigration):

    to_name_translation = {
        u'': None,
        u'(bwijnen@lucent.com) Bert Wijnen': None,
        u'(lyong@ciena.com)Lyndon Ong': None,
        u'(sob@harvard.edu) Scott Bradner': None,
        u'(sob@harvard.edu)Scott Bradner': None,
        u'3GPP SA WG4': None,
        u'3GPP SA2': None,
        u'3GPP TSG CT WG4': None,
        u'3GPP TSG RAN WG2': None,
        u'3GPP TSG SA WG4': [u'3GPP-TSG-SA-WG4'],
        u'3GPP, 3GPP2, ARIB, ATIS, CCSA, ETSI, ETSI-DECT, ETSI-BRAN, IEEE, IETF,': None,
        u'3GPP/IETF and 3GPP/ITU-T Co-ordinator': None,
        u'ACIF, ARIB, ATIS, CCSA, ETSI, IEEE, IETF, ISACC, TIA, TTA, TTC': None,
        u'ASON-related Work': None,
        u'ATIS': None,
        u'BBF': None,
        u'BMWG': [u'bmwg'],
        u'Bert Wijnen and the IETF O & M Area': None,
        u'Bert Wijnen, Bernard Aboba and the IETF': None,
        u'CCAMP WG co-chairs and IEEE-IETF': None,
        u'CCAMP WG co-chairs and IEEE-IETF liaisons': None,
        u'Completes action above Scott Bradner, Area co-Director (sob@harvard.edu)': None,
        u'DLNA': None,
        u'DONE': None,
        u'DSL Forum': None,
        u'DSL Forum Architecture & Transport Working Group': None,
        u'DVB IPI': None,
        u'DVB TM-IPI, ETSI TISPAN, ATIS IIF, IETF RMT, IETF FECFRAME': None,
        u'EAP Method Update Working Group': None,
        u'ETSI AT working group Digital': None,
        u'ETSI TC HF': None,
        u'ETSI TISPAN': None,
        u'G.7712 Editor, ITU-T SG15Q14 Rapporteur, ITU-T SG15': None,
        u'Generic EAP Encapsulation': None,
        u'Harald Alvestrand': None,
        u'IAB and IETF Routing Area Directors': [u'iab', 'rtg'],
        u'IAB, IESG': [u'iab', 'iesg'],
        u'IANA': [u'iana'],
        u'ICANN, IETF/IAB, NRO and ACSIS': None,
        u'IEEE 802': None,
        u'IEEE NGSON Study Group': None,
        u'IEEE802.1': [u'ieee-8021'],
        u'IESG members, IAB members': [u'iesg', u'iab'],
        u'IESG, IETF-RAI': [u'iesg', u'rai'],
        u'IESG/IAB Chair': [u'iesg', u'iab'],
        u'IETF  PWE3 and TICTOC': [u'pwe3', u'tictoc'],
        u'IETF (CCAMP, PCE and MPLS WGs)': [u'ccamp', u'pce', u'mpls'],
        u'IETF (Management)': None,
        u'IETF (SAVI and V6OPS WGS, OPS Area and INT Area)': [u'savi', u'v6ops', u'ops', u'int'],
        u'IETF (Sub-IP & Transport Areas)': [u'sub', u'tsv'],
        u'IETF (and others)': None,
        u'IETF (ccamp, pce and mpls WGs)': [u'ccamp', u'pce', u'mpls'],
        u'IETF 6MAN WG, IETF Internet Area': [u'6man', u'int'],
        u'IETF AVT WG, ITU-T SG11': [u'avt', u'itu-t-sg-11'],
        u'IETF CCAMP WG, Routing Area Directors': [u'ccamp', u'rtg'],
        u'IETF CCAMP and MPLS WGs': [u'ccamp', u'mpls'],
        u'IETF CCAMP and MPLS WGs and the Routing Area Directors of the IETF': [u'ccamp', u'mpls', u'rtg'],
        u'IETF CCAMP and PCE WGs': [u'ccamp', u'pce'],
        u'IETF CCAMP, IETF Routing Area Directors': [u'ccamp', u'rtg'],
        u'IETF CCAMP, PCE and MPLS WGs': [u'ccamp', u'pce', u'mpls'],
        u'IETF Charter group on Authority to Citizen Alert (ATOCA)': [u'atoca'],
        u'IETF DNSOP WG, SAAG, IAB': [u'dnsop', u'saag', u'iab'],
        u'IETF IAB, IETF IESG': [u'iab', u'ietf', u'iesg'],
        u'IETF IESG, IAB, PWE3 WG, MPLS WG, routing and internet Area Directors': [u'iesg', u'iab', u'pwe3', u'mpls', u'rtg', u'int'],
        u'IETF IPPM, IETF AVT': [u'ippm', u'avt'],
        u'IETF Internet Area; IETF MIF WG; IETF v6ops WG; IETF 6man WG; IETF softwire WG;  IETF Operations and Management Area': [u'int', u'mif', u'v6ops', u'6man', u'softwire', u'ops'],
        u'IETF Liaison to the ITU on MPLS and PWE3 WG Co-Chair': [u'itu-t-mpls', u'pwe3'],
        u'IETF MEAD Team': None,
        u'IETF MEAD team': None,
        u'IETF MEXT WG': ['mext'],
        u'IETF MIPSHOP-WG': [u'mipshop'],
        u'IETF MPLS & PWE3': [u'mpls', u'pwe3'],
        u'IETF MPLS WG, CC: IETF CCAMP and PWE3  WGs': [u'mpls', u'ccamp', u'pwe3'],
        u'IETF MPLS WG, CC: MFA Forum': None,
        u'IETF MPLS WG, IAB, IESG': [u'mpls', u'iab', u'iesg'],
        u'IETF MPLS WG, IETF IAB and IESG': [u'mpls', u'iab', u'iesg'],
        u'IETF MPLS WG, IETF PWE3 WG, Broadband Forum': [u'mpls', u'pwe3', u'broadband-forum'],
        u'IETF MPLS and GMPLS': None,
        u'IETF MPLS and PWE3 WG, MFA Forum, ITU-T Q7/13': None,
        u'IETF MPLS liaison representative': [u'mpls'],
        u'IETF MPLS, CCAMP and PWE3  WGs': [u'mpls', u'ccamp', u'pwe3'],
        u'IETF MPLS, CCAMP, PWE3 and L2VPN': [u'mpls', u'ccamp', u'pwe3', u'l2vpn'],
        u'IETF MPLS, PWE WGs (Info: IETF MEAD team)': None,
        u'IETF Mead Team': None,
        u'IETF NSIS WG Chairs, IETF TSV Area Directors, IESG members, IAB members': [u'nsis', u'tsv', u'iesg', u'iab'],
        u'IETF PWE3 and L2VPN': [u'pwe3', u'l2vpn'],
        u'IETF PWE3 and L2VPN Working Groups': [u'pwe3', u'l2vpn'],
        u'IETF PWE3 and MPLS WGs': [u'pwe3', u'mpls'],
        u'IETF PWE3 and MPLS Working Groups': [u'pwe3', u'mpls'],
        u'IETF PWE3, MPLS working groups': [u'pwe3', u'mpls'],
        u'IETF RAI and IESG': [u'rai', 'iesg'],
        u'IETF Real-time Applications and Infrastructure Area Director': [u'rai'],
        u'IETF Routing Area, the MPLS and CCAMP working groups': [u'rtg', u'mpls', u'ccamp'],
        u'IETF Routing and Transport areas': [u'rtg', u'tsv'],
        u'IETF SIP related Working Groups and IESG': None,
        u'IETF Transport and Internat Areas': [u'tsv', u'int'],
        u'IETF WG MPLS': [u'mpls'],
        u'IETF Working Groups IEPREP, TSV, NSIS': [u'ieprep', u'tsv', u'nsis'],
        u'IETF and Harald Alvestrand': None,
        u'IETF and IAB': [u'ietf', u'iab'],
        u'IETF pwe3, mpls WGs': [u'pwe3', u'mpls'],
        u'IETF re RoHC': [u'rohc'],
        u'IETF \u2013 Internet Area Directors, Internet Area Working Groups': [u'int'],
        u'IETF, IAB': [u'ietf', u'iab'],
        u'IETF/IAB': [u'ietf', u'iab'],
        u'IETF/IAB, NRO, ICANN and ACSIS': None,
        u'IETF/IAB/IESG': [u'ietf', u'iab', u'iesg'],
        u'IETF/PWE3 and L2VPN WGs': [u'pwe3', u'l2vpn'],
        u'ISIS': [u'isis'],
        u'ISMA': None,
        u'ISO/IEC JTC': None,
        u'ISO/IEC JTC 1/SC 29/WG 1': None,
        u'ISOC': [u'isoc'],
        u'ISOC/IAB Liaison': [u'isoc', 'iab'],
        u'ITU': [u'itu-t'],
        u'ITU IPv6 Group': None,
        u'ITU Q12/15 and Q14/15': None,
        u'ITU SG 16 Q8, 9, 10/16': None,
        u'ITU SG13': [u'itu-t-sg-13'],
        u'ITU SG15': [u'itu-t-sg-15'],
        u'ITU-R': [u'itu-r'],
        u'ITU-R WP8F & IETF': None,
        u'ITU-SG15': [u'itu-t-sg-15'],
        u'ITU-SG2': [u'itu-t-sg-2'],
        u'ITU-T JCA-IdM': None,
        u'ITU-T Q1/SG15': None,
        u'ITU-T Q10/15': None,
        u'ITU-T Q12/15 and Q14/15': None,
        u'ITU-T Q14/15': None,
        u'ITU-T Q14/15 - Mr. Kam Lam, Rapporteur': None,
        u'ITU-T Q14/15, ITU-T Q11/15': None,
        u'ITU-T Q3/15': None,
        u'ITU-T Q5/13 (recently renamed ITU-T Q7/13)': None,
        u'ITU-T Q7/SG13': None,
        u'ITU-T Question 14/15': None,
        u'ITU-T Question 3/15': None,
        u'ITU-T SG 11 and ITU-T TSAG': [u'itu-t-sg-11', u'itu-t-tsag'],
        u'ITU-T SG 11, ITU-T Q.5/11, ITU-T WP 2/11': None,
        u'ITU-T SG 13 (ITU-T SG 11 and SG 12 for information)': None,
        u'ITU-T SG 13 (ITU-T SG 11 for information)': None,
        u'ITU-T SG 13, SG 15': [u'itu-t-sg-13', u'itu-t-sg-15'],
        u'ITU-T SG 15 <tsbsg15@itu.int, greg.jones@itu.int>': [u'itu-t-sg-15'],
        u'ITU-T SG 15 Q9, Q10, Q12 and Q14': [u'itu-t-sg15-q9-q10-q12-and-q14'],
        u'ITU-T SG 15, Q.14/15': None,
        u'ITU-T SG 15, Q9, Q11, Q12, Q14': None,
        u'ITU-T SG 17 Q.2/17': None,
        u'ITU-T SG 4': None,
        u'ITU-T SG 4, 9, 11, 13, 16 and IETF': None,
        u'ITU-T SG-15': [u'itu-t-sg-15'],
        u'ITU-T SG-2': [u'itu-t-sg-2'],
        u'ITU-T SG11': [u'itu-t-sg-11'],
        u'ITU-T SG12, SG13, ATIS, TIA, IEC, IETF ccamp WG, IEEE 802.1, 802.3, OIF, Metro Ethernet Forum, ATM Forum': None,
        u'ITU-T SG13': [u'itu-t-sg-13'],
        u'ITU-T SG13 and SG15': [u'itu-t-sg-13', u'itu-t-sg-15'],
        u'ITU-T SG15': [u'itu-t-sg-15'],
        u'ITU-T SG15 (Optical Control Plane)': [u'itu-t-sg-15'],
        u'ITU-T SG15 Q10': None,
        u'ITU-T SG15 Q10, Q12': None,
        u'ITU-T SG15 Q12': None,
        u'ITU-T SG15 Q14': None,
        u'ITU-T SG15 Q6': None,
        u'ITU-T SG15 Q9, Q10, Q12 and Q14': [u'itu-t-sg15-q9-q10-q12-and-q14'],
        u'ITU-T SG15 Q9, Q11, Q12 and Q14': None,
        u'ITU-T SG15 Question 12': None,
        u'ITU-T SG15 Question 3': None,
        u'ITU-T SG15 Question 6': None,
        u'ITU-T SG15 Question 6, Question 12, and Question 14': None,
        u'ITU-T SG15 Question 9': None,
        u'ITU-T SG15 Questions 12 and 14': None,
        u'ITU-T SG15 and Q14/15': None,
        u'ITU-T SG15, Q 9/15, Q 10/15, Q 12/15 and Q 14/15': [u'itu-t-sg15-q9-q10-q12-and-q14'],
        u'ITU-T SG15, Q 9/15, Q10/15, Q12/15 and Q14/15': [u'itu-t-sg15-q9-q10-q12-and-q14'],
        u'ITU-T SG15, Q9, Q11, Q12 and Q14': None,
        u'ITU-T SG16': [u'itu-t-sg-16'],
        u'ITU-T SG17': [u'itu-t-sg-17'],
        u'ITU-T SG2': [u'itu-t-sg-2'],
        u'ITU-T SG2 <tsbsg2@itu.int>': [u'itu-t-sg-2'],
        u'ITU-T SG2 Q 1/2': None,
        u'ITU-T SG4': None,
        u'ITU-T SG4, ITU-T SG15, ITU-T NGNM Focus group, 3GPP SA5, 3GPP2, ATIS/TMOC, TMF, IETF Management, ETSI BRAN': None,
        u'ITU-T SGs, ITU-R WGs, ITU-D SG2 and the IETF': None,
        u'ITU-T SGs: 2 (info), 4, 9, 11, 12, 13, 17, 19; ITU-R SGs: 1, 4, 5, 6; ITU-D SG 2; Focus Group on \u2018From/In/To Cars II\u2019 (ITU-T SG 12); ISO TC 22 SC3 and TC 204 ; IEEE 802, 802.11 (WiFi), 802.15.1 (Bluetooth); AUTOSAR WPII-1.1, OSGi VEG, IrDA and JSR298 Tele': None,
        u'ITU-T SQ15 Question 14': None,
        u'ITU-T Study Group 11': [u'itu-t-sg-11'],
        u'ITU-T Study Group 11 <tsg11gen@itu.int>': [u'itu-t-sg-11'],
        u'ITU-T Study Group 13': [u'itu-t-sg-13'],
        u'ITU-T Study Group 15': [u'itu-t-sg-15'],
        u'ITU-T Study Group 15 <greg.jones@itu.int>': [u'itu-t-sg-15'],
        u'ITU-T Study Group 15 Q4 <rlstuart@ieee.org>': None,
        u'ITU-T Study Group 15 Question 14': None,
        u'ITU-T Study Group 15 Question 3': None,
        u'ITU-T Study Group 15 Question 6': None,
        u'ITU-T TSAG External Relations Group': [u'itu-t-tsag'],
        u'ITU-T Working Party 3/13 and ITU-T Question 11/13': None,
        u'ITU-T and ITU-T Study Group 13': [u'itu-t', u'itu-t-sg-13'],
        u'ITU-T, ITU SG13': [u'itu-t', u'itu-t-sg-13'],
        u'ITU-T-SG13': [u'itu-t-sg-13'],
        u'ITU-T/FG Cloud': None,
        u'ITU-T/SG11': [u'itu-t-sg-11'],
        u'ITU-T/Study Group 11': [u'itu-t-sg-11'],
        u'Kam Lam, Rapporteur for Question 14 of ITU-T SG15': None,
        u'Kam Lam, Rapporteur for Question 14 of ITU-T Study Group 15': None,
        u'Lyndon Ong (lyong@ciena.com)': None,
        u'MFA Forum': None,
        u'MPLS and Frame Relay Alliance': None,
        u'Mr. Kam Lam, Rapporteur for Question 14 of ITU-T Study Group 15': None,
        u'National, Multi-National or Regional Organizations': None,
        u'OMA': None,
        u'OMA MEM': None,
        u'OMA MWG': None,
        u'OMA MWG MEM Sub Working Group': None,
        u'OMA TP': None,
        u'OPS ADs (Randy Bush and Bert Wijnen)': [u'ops'],
        u'OPS Area Director Bert Wijnen': [u'ops'],
        u'Open IPTV Forum': None,
        u'Open Mobile Alliance Broadcasting  Working Group': None,
        u'Open Mobile Alliance, PAG Working Group': None,
        u'PDNR ITU-R M.[IP CHAR]': None,
        u'PWE WG': None,
        u'Phase 1 report to SG 4': None,
        u'Q7/13': None,
        u'Rao Cherukuri, Chair MPLS and Frame Relay Alliance Technical Committee': None,
        u'Rao Cherukuri, Chairman, MPLS and Frame Relay Alliance Technical Committee': None,
        u'SA2, T2, OMA TP, S3': None,
        u'SAVI WG, V6OPS WG, OPS AREA,  INT AREA': [u'savi', u'v6ops', u'ops', u'int'],
        u'SC 29/WG11': [u'isoiec-jtc-1sc-29wg-11'],
        u'SC29/WG11': [u'isoiec-jtc-1sc-29wg-11'],
        u'SG 15,Questions 3,9, 11,12, 14 and WP 3/15': None,
        u'SG-13, Q.3/13, Q.9/13 and TSAG': None,
        u'SG13, SG13 WP4': None,
        u'SG15 Q9': None,
        u'SG15, Q9, Q10, Q12 and Q14': [u'itu-t-sg15-q9-q10-q12-and-q14'],
        u'SG15, Q9, Q10, Q12, Q14': [u'itu-t-sg15-q9-q10-q12-and-q14'],
        u'SG15, Q9, Q10, Q12, and Q14': [u'itu-t-sg15-q9-q10-q12-and-q14'],
        u'SG15, Q9, Q11, Q12 and Q14': None,
        u'SG17, SG13, SG11, JCA-NID, ETSI TISPAN WG4, 3GPP TSG CT4, IESG': None,
        u'SG4': None,
        u'SIP aand SIPPING WGs': [u'sip', u'sipping'],
        u'SIP, SIPPING, SIMPLE WGs': [u'sip', u'sipping', u'simple'],
        u'SUB-IP and Transport Areas': [u'sub', u'tsv'],
        u'Scott Bradner': None,
        u'Scott Bradner (sob@harvard.edu)': None,
        u'Scott Bradner (sob@harvard.edu) Done': None,
        u'SubIP ADs (sob@harvard.edu,bwijnen@lucent.com)': [u'sub'],
        u'TEWG, MPLS, CCAMP WGs': [u'tewg', u'mpls', u'ccamp'],
        u'TRILL WG co-chairs and IEEE-IETF liaisons': None,
        u'TRILL WG co-chairs, ADs, and IEEE-IETF liaisons': None,
        u'TSG-X Corr to IETF re MIP6 Bootstrapping': None,
        u'The IAB': [u'iab'],
        u'The IESG': [u'iesg'],
        u'The IESG and the IAB': [u'iesg', u'iab'],
        u'The IETF': [u'ietf'],
        u'Tom Taylor (taylor@nortelnetworks.com), Megaco WG Chair': [u'megaco'],
        u'Transport ADs (Allison Mankin and Scott Bradner)': [u'tsv'],
        u'Transport Area Directors': [u'tsv'],
        u'Unicode Consortium': None,
        u'Unicode Technical Committee': None,
        u'Various IETF WGs': None,
        u'W3C Geolocation WG': None,
        u'W3C Geolocation Working Group': None,
        u'W3C Multimedia Interaction Work Group': None,
        u'WiFi Alliance and Wireless Broadband Alliance': None,
        u'chair@ietf.org': None,
        u'gonzalo.camarillo@ericsson.com': None,
        u'tsbdir@itu.int': None
    }

    def forwards(self, orm):
        for liaison in orm['liaisons.LiaisonStatement'].objects.all():
            if liaison.to_group:
                liaison.to_groups.add(liaison.to_group)
            elif liaison.to_name in self.to_name_translation and self.to_name_translation[liaison.to_name]:
                for acr in self.to_name_translation[liaison.to_name]:
                    liaison.to_groups.add(orm['group.Group'].objects.get(acronym=acr))

    def backwards(self, orm):
        "Write your backwards methods here."

    models = {
        u'auth.group': {
            'Meta': {'object_name': 'Group'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '80'}),
            'permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'})
        },
        u'auth.permission': {
            'Meta': {'ordering': "(u'content_type__app_label', u'content_type__model', u'codename')", 'unique_together': "((u'content_type', u'codename'),)", 'object_name': 'Permission'},
            'codename': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['contenttypes.ContentType']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        u'auth.user': {
            'Meta': {'object_name': 'User'},
            'date_joined': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'email': ('django.db.models.fields.EmailField', [], {'max_length': '75', 'blank': 'True'}),
            'first_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'groups': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "u'user_set'", 'blank': 'True', 'to': u"orm['auth.Group']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_staff': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_superuser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'last_login': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'password': ('django.db.models.fields.CharField', [], {'max_length': '128'}),
            'user_permissions': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "u'user_set'", 'blank': 'True', 'to': u"orm['auth.Permission']"}),
            'username': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '64'})
        },
        u'contenttypes.contenttype': {
            'Meta': {'ordering': "('name',)", 'unique_together': "(('app_label', 'model'),)", 'object_name': 'ContentType', 'db_table': "'django_content_type'"},
            'app_label': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'model': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        },
        u'doc.document': {
            'Meta': {'object_name': 'Document'},
            'abstract': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ad': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'ad_document_set'", 'null': 'True', 'to': u"orm['person.Person']"}),
            'authors': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['person.Email']", 'symmetrical': 'False', 'through': u"orm['doc.DocumentAuthor']", 'blank': 'True'}),
            'expires': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'external_url': ('django.db.models.fields.URLField', [], {'max_length': '200', 'blank': 'True'}),
            'group': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['group.Group']", 'null': 'True', 'blank': 'True'}),
            'intended_std_level': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['name.IntendedStdLevelName']", 'null': 'True', 'blank': 'True'}),
            'internal_comments': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'primary_key': 'True'}),
            'note': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'notify': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'order': ('django.db.models.fields.IntegerField', [], {'default': '1', 'blank': 'True'}),
            'pages': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'rev': ('django.db.models.fields.CharField', [], {'max_length': '16', 'blank': 'True'}),
            'shepherd': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'shepherd_document_set'", 'null': 'True', 'to': u"orm['person.Person']"}),
            'states': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['doc.State']", 'symmetrical': 'False', 'blank': 'True'}),
            'std_level': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['name.StdLevelName']", 'null': 'True', 'blank': 'True'}),
            'stream': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['name.StreamName']", 'null': 'True', 'blank': 'True'}),
            'tags': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'to': u"orm['name.DocTagName']", 'null': 'True', 'blank': 'True'}),
            'time': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'title': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'type': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['name.DocTypeName']", 'null': 'True', 'blank': 'True'})
        },
        u'doc.documentauthor': {
            'Meta': {'ordering': "['document', 'order']", 'object_name': 'DocumentAuthor'},
            'author': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['person.Email']"}),
            'document': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['doc.Document']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'order': ('django.db.models.fields.IntegerField', [], {'default': '1'})
        },
        u'doc.state': {
            'Meta': {'ordering': "['type', 'order']", 'object_name': 'State'},
            'desc': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'next_states': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "'previous_states'", 'blank': 'True', 'to': u"orm['doc.State']"}),
            'order': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'slug': ('django.db.models.fields.SlugField', [], {'max_length': '50'}),
            'type': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['doc.StateType']"}),
            'used': ('django.db.models.fields.BooleanField', [], {'default': 'True'})
        },
        u'doc.statetype': {
            'Meta': {'object_name': 'StateType'},
            'label': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'slug': ('django.db.models.fields.CharField', [], {'max_length': '30', 'primary_key': 'True'})
        },
        u'group.group': {
            'Meta': {'object_name': 'Group'},
            'acronym': ('django.db.models.fields.SlugField', [], {'unique': 'True', 'max_length': '40'}),
            'ad': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['person.Person']", 'null': 'True', 'blank': 'True'}),
            'charter': ('django.db.models.fields.related.OneToOneField', [], {'blank': 'True', 'related_name': "'chartered_group'", 'unique': 'True', 'null': 'True', 'to': u"orm['doc.Document']"}),
            'comments': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'list_archive': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'list_email': ('django.db.models.fields.CharField', [], {'max_length': '64', 'blank': 'True'}),
            'list_subscribe': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '80'}),
            'parent': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['group.Group']", 'null': 'True', 'blank': 'True'}),
            'state': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['name.GroupStateName']", 'null': 'True'}),
            'time': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'type': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['name.GroupTypeName']", 'null': 'True'}),
            'unused_states': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['doc.State']", 'symmetrical': 'False', 'blank': 'True'}),
            'unused_tags': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['name.DocTagName']", 'symmetrical': 'False', 'blank': 'True'})
        },
        u'liaisons.liaisonstatement': {
            'Meta': {'object_name': 'LiaisonStatement'},
            'action_holder_contacts': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'action_taken': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'approved': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'attachments': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['doc.Document']", 'symmetrical': 'False', 'through': u"orm['liaisons.LiaisonStatementAttachments']", 'blank': 'True'}),
            'body': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'cc_contacts': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'deadline': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'from_contact': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['person.Email']", 'null': 'True', 'blank': 'True'}),
            'from_group': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'liaisonstatement_from_set'", 'null': 'True', 'to': u"orm['group.Group']"}),
            'from_groups': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "'liaisonsatement_from_set'", 'blank': 'True', 'to': u"orm['group.Group']"}),
            'from_name': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'other_identifiers': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'purpose': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['name.LiaisonStatementPurposeName']"}),
            'related_to': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['liaisons.LiaisonStatement']", 'null': 'True', 'blank': 'True'}),
            'reply_to': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'response_contacts': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'state': ('django.db.models.fields.related.ForeignKey', [], {'default': "'pending'", 'to': u"orm['name.LiaisonStatementState']"}),
            'submitted': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'technical_contacts': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'title': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'to_contacts': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'to_group': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'liaisonstatement_to_set'", 'null': 'True', 'to': u"orm['group.Group']"}),
            'to_groups': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "'liaisonsatement_to_set'", 'blank': 'True', 'to': u"orm['group.Group']"}),
            'to_name': ('django.db.models.fields.CharField', [], {'max_length': '255'})
        },
        u'liaisons.liaisonstatementattachments': {
            'Meta': {'object_name': 'LiaisonStatementAttachments'},
            'document': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['doc.Document']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'removed': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'statement': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['liaisons.LiaisonStatement']"})
        },
        u'liaisons.liaisonstatementevent': {
            'Meta': {'object_name': 'LiaisonStatementEvent'},
            'by': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['person.Person']"}),
            'desc': ('django.db.models.fields.TextField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'statement': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['liaisons.LiaisonStatement']"}),
            'time': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'type': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['name.LiaisonStatementEventTypeName']"})
        },
        u'liaisons.liaisonstatementgroupcontacts': {
            'Meta': {'object_name': 'LiaisonStatementGroupContacts'},
            'default_reply_to': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['group.Group']", 'unique': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        u'liaisons.relatedliaisonstatement': {
            'Meta': {'object_name': 'RelatedLiaisonStatement'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'relationship': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['name.DocRelationshipName']"}),
            'source': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'source_of_set'", 'to': u"orm['liaisons.LiaisonStatement']"}),
            'target': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'target_of_set'", 'to': u"orm['liaisons.LiaisonStatement']"})
        },
        u'name.docrelationshipname': {
            'Meta': {'ordering': "['order']", 'object_name': 'DocRelationshipName'},
            'desc': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'order': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'revname': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'slug': ('django.db.models.fields.CharField', [], {'max_length': '8', 'primary_key': 'True'}),
            'used': ('django.db.models.fields.BooleanField', [], {'default': 'True'})
        },
        u'name.doctagname': {
            'Meta': {'ordering': "['order']", 'object_name': 'DocTagName'},
            'desc': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'order': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'slug': ('django.db.models.fields.CharField', [], {'max_length': '8', 'primary_key': 'True'}),
            'used': ('django.db.models.fields.BooleanField', [], {'default': 'True'})
        },
        u'name.doctypename': {
            'Meta': {'ordering': "['order']", 'object_name': 'DocTypeName'},
            'desc': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'order': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'slug': ('django.db.models.fields.CharField', [], {'max_length': '8', 'primary_key': 'True'}),
            'used': ('django.db.models.fields.BooleanField', [], {'default': 'True'})
        },
        u'name.groupstatename': {
            'Meta': {'ordering': "['order']", 'object_name': 'GroupStateName'},
            'desc': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'order': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'slug': ('django.db.models.fields.CharField', [], {'max_length': '8', 'primary_key': 'True'}),
            'used': ('django.db.models.fields.BooleanField', [], {'default': 'True'})
        },
        u'name.grouptypename': {
            'Meta': {'ordering': "['order']", 'object_name': 'GroupTypeName'},
            'desc': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'order': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'slug': ('django.db.models.fields.CharField', [], {'max_length': '8', 'primary_key': 'True'}),
            'used': ('django.db.models.fields.BooleanField', [], {'default': 'True'})
        },
        u'name.intendedstdlevelname': {
            'Meta': {'ordering': "['order']", 'object_name': 'IntendedStdLevelName'},
            'desc': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'order': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'slug': ('django.db.models.fields.CharField', [], {'max_length': '8', 'primary_key': 'True'}),
            'used': ('django.db.models.fields.BooleanField', [], {'default': 'True'})
        },
        u'name.liaisonstatementeventtypename': {
            'Meta': {'ordering': "['order']", 'object_name': 'LiaisonStatementEventTypeName'},
            'desc': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'order': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'slug': ('django.db.models.fields.CharField', [], {'max_length': '8', 'primary_key': 'True'}),
            'used': ('django.db.models.fields.BooleanField', [], {'default': 'True'})
        },
        u'name.liaisonstatementpurposename': {
            'Meta': {'ordering': "['order']", 'object_name': 'LiaisonStatementPurposeName'},
            'desc': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'order': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'slug': ('django.db.models.fields.CharField', [], {'max_length': '8', 'primary_key': 'True'}),
            'used': ('django.db.models.fields.BooleanField', [], {'default': 'True'})
        },
        u'name.stdlevelname': {
            'Meta': {'ordering': "['order']", 'object_name': 'StdLevelName'},
            'desc': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'order': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'slug': ('django.db.models.fields.CharField', [], {'max_length': '8', 'primary_key': 'True'}),
            'used': ('django.db.models.fields.BooleanField', [], {'default': 'True'})
        },
        u'name.streamname': {
            'Meta': {'ordering': "['order']", 'object_name': 'StreamName'},
            'desc': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'order': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'slug': ('django.db.models.fields.CharField', [], {'max_length': '8', 'primary_key': 'True'}),
            'used': ('django.db.models.fields.BooleanField', [], {'default': 'True'})
        },
        u'name.liaisonstatementstate': {
            'Meta': {'ordering': "['order']", 'object_name': 'LiaisonStatementState'},
            'desc': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'order': ('django.db.models.fields.IntegerField', [], {'default': '0'}),
            'slug': ('django.db.models.fields.CharField', [], {'max_length': '8', 'primary_key': 'True'}),
            'used': ('django.db.models.fields.BooleanField', [], {'default': 'True'})
        },
        u'person.email': {
            'Meta': {'object_name': 'Email'},
            'active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'address': ('django.db.models.fields.CharField', [], {'max_length': '64', 'primary_key': 'True'}),
            'person': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['person.Person']", 'null': 'True'}),
            'time': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'})
        },
        u'person.person': {
            'Meta': {'object_name': 'Person'},
            'address': ('django.db.models.fields.TextField', [], {'max_length': '255', 'blank': 'True'}),
            'affiliation': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'ascii': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'ascii_short': ('django.db.models.fields.CharField', [], {'max_length': '32', 'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_index': 'True'}),
            'time': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'user': ('django.db.models.fields.related.OneToOneField', [], {'to': u"orm['auth.User']", 'unique': 'True', 'null': 'True', 'blank': 'True'})
        }
    }

    complete_apps = ['liaisons']
    symmetrical = True
