# Copyright The IETF Trust 2019-2020, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-30 13:37


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0020_add_uses_milestone_dates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmilestone',
            options={'ordering': ['order', 'due', 'id']},
        ),
        migrations.AlterModelOptions(
            name='groupmilestonehistory',
            options={'ordering': ['order', 'due', 'id']},
        ),
        migrations.AddField(
            model_name='groupmilestone',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmilestonehistory',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmilestone',
            name='due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmilestonehistory',
            name='due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
