# -*- coding: utf-8 -*-
# Copyright The IETF Trust 2019-2020, All Rights Reserved
# Generated by Django 1.11.22 on 2019-07-03 13:44


import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribed',
            name='email',
            field=models.CharField(max_length=128, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
