# Generated by Django 2.2.28 on 2023-03-20 19:22

from typing import List, Tuple
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: List[Tuple[str, str]] = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('variables', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
