# Generated by Django 4.2.30 on 2026-05-06 07:49

from django.db import migrations, models

INITIAL_MAIN_NAMES = ['Akamai', 'Alcatel', 'Apple', 'AT&T', 'Avaya', 'BBN', 'Cabletron', 'CERNET', 'Check Point', 'Ciena', 'Cisco', 'Fastmail', 'Fujitsu', 
                      'Futurewei', 'Google', 'Hitachi', 'HPE', 'Huawei', 'IBM', 'INRIA','Intel', 'IEEE', 'JHU', 'Juniper', 
                      'Lucent', 'MCI', 'Meta', 'Microsoft', 'MIT', 'Motorola',
                      'NASA', 'NEC', 'Nokia', 'Nortel', 'NTT', 'Oracle', 'Pantheon', 'Qualcomm', 'Siemens', 'Softbank', 'Telefonica', 'T-Mobile', 'Telia', 'Tencent',
                      'UUNET', 'VeriSign', 'Verizon', 'Videotron','Vodafone', 'ZTE']

NEW_COUNTRY_ALIASES = [
        {'alias': 'Belgie', 'country': 'Belgium'},
    ]

def forward(apps, schema_editor):
    """Add initial main names."""
    AffiliationMainName = apps.get_model('stats', 'AffiliationMainName')
    for name in INITIAL_MAIN_NAMES:
        AffiliationMainName.objects.get_or_create(main_name=name)

    CountryAlias = apps.get_model('stats', 'CountryAlias')
    CountryName = apps.get_model('name', 'CountryName')

    for entry in NEW_COUNTRY_ALIASES:
        country = CountryName.objects.get(name=entry['country'])
        CountryAlias.objects.get_or_create(
            alias=entry['alias'],
            defaults={'country': country},
        )


def backward(apps, schema_editor):
    """Remove initial main names."""
    AffiliationMainName = apps.get_model('stats', 'AffiliationMainName')
    AffiliationMainName.objects.filter(main_name__in=INITIAL_MAIN_NAMES).delete()

    CountryAlias = apps.get_model('stats', 'CountryAlias')
    aliases_to_remove = [alias for alias, _ in NEW_COUNTRY_ALIASES]
    CountryAlias.objects.filter(alias__in=aliases_to_remove).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_fix_meeting_registration_reg_type"),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliationMainName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'affiliation main name',
                'verbose_name_plural': 'affiliations main names',
                'ordering': ['main_name'],
            },
        ),
        migrations.RunPython(forward, backward),
    ]
