# Generated by Django 2.0.13 on 2020-06-09 04:39

from django.db import migrations, models


def forward(apps, schema_editor):
    MeetingRegistration = apps.get_model('stats', 'MeetingRegistration')
    # Set attended=True on all existing records,
    #
    # Going forward, this will be unset on registration
    # (ietf.api.views.api_new_meeting_registration()), and set on attendee
    # import (ietf.stats.utils.get_meeting_registration_data() )
    MeetingRegistration.objects.update(attended=True)

def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_add_meetingregistration_fields'),
        ('group', '0029_add_used_roles_and_default_used_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingregistration',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forward, reverse),
    ]
