# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 13:55
from __future__ import unicode_literals

from django.db import migrations

from ietf.stats.utils import get_registration_data

def forward(apps, schema_editor):
    Registration = apps.get_model('stats', 'Registration')
    Meeting = apps.get_model('meeting', 'Meeting')
    for meeting in Meeting.objects.filter(number__in=[ str(n) for n in range(72,99) ]):
        total = get_registration_data(meeting)
        print "Meeting {}: {}".format(meeting.number, total)
    
def backward(apps, schema_editor):
    Registration = apps.get_model('stats', 'Registration')
    Registration.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_registration_registrationstats'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
