# Generated by Django 2.2.26 on 2022-01-19 16:36

from django.db import migrations


def forward(apps, schema_editor):
    '''Split records that have 2 reg_types into two separate records'''
    MeetingRegistration = apps.get_model('stats', 'MeetingRegistration')
    meetings = [108, 109, 110, 111, 112, 113]
    for reg in MeetingRegistration.objects.filter(meeting__number__in=meetings):
        reg_types = reg.reg_type.split()
        if len(reg_types) == 2:
            reg.reg_type = reg_types[0]
            reg.save()
            # create copy
            reg.pk = None
            reg.reg_type = reg_types[1]
            reg.save()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_meetingregistration_attended'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
