# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 12:00
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Q

def strip_spaces(apps, schema_editor):
    MeetingRegistration = apps.get_model("stats", "MeetingRegistration")
    for reg in MeetingRegistration.objects.filter(Q(first_name__startswith=' ') |
                                                  Q(first_name__endswith=' ')).distinct():
        reg.first_name = reg.first_name.strip()
        reg.save()

    for reg in MeetingRegistration.objects.filter(Q(last_name__startswith=' ') |
                                                  Q(last_name__endswith=' ')).distinct():
        reg.last_name = reg.last_name.strip()
        reg.save()

    for reg in MeetingRegistration.objects.filter(Q(affiliation__startswith=' ') |
                                                  Q(affiliation__endswith=' ')).distinct():
        reg.affiliation = reg.affiliation.strip()
        reg.save()

    for reg in MeetingRegistration.objects.filter(Q(email__startswith=' ') |
                                                  Q(email__endswith=' ')).distinct():
        reg.email = reg.email.strip()
        reg.save()

class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_meetingregistration_email'),
    ]

    operations = [
        migrations.RunPython(strip_spaces, migrations.RunPython.noop),
    ]
