# Generated by Django 2.2.28 on 2023-03-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iesg', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='telechatdate',
            index=models.Index(fields=['-date'], name='iesg_telech_date_a0e0ed_idx'),
        ),
    ]
