# Generated by Django 4.2.13 on 2024-06-21 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iesg", "0002_telechatagendacontent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Telechat",
        ),
    ]
