# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-18 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_groupfeatures_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalgroupfeatures',
            name='agenda_type',
            field=models.ForeignKey(blank=True, db_constraint=False, default=b'ietf', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='name.AgendaTypeName'),
        ),
    ]
