# Generated by Django 4.2.23 on 2025-08-15 16:46

from django.db import migrations, models
import ietf.group.models
import ietf.name.models
import ietf.utils.db
import ietf.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0007_used_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="used_roles",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Leave an empty list to get the group_type's default used roles",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="groupfeatures",
            name="admin_roles",
            field=ietf.utils.db.EmptyAwareJSONField(
                default=ietf.group.models.default_admin_roles, max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="groupfeatures",
            name="default_used_roles",
            field=ietf.utils.db.EmptyAwareJSONField(default=list, max_length=256),
        ),
        migrations.AlterField(
            model_name="groupfeatures",
            name="docman_roles",
            field=ietf.utils.db.EmptyAwareJSONField(
                default=ietf.group.models.default_docman_roles, max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="groupfeatures",
            name="groupman_authroles",
            field=ietf.utils.db.EmptyAwareJSONField(
                default=ietf.group.models.default_groupman_authroles, max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="groupfeatures",
            name="groupman_roles",
            field=ietf.utils.db.EmptyAwareJSONField(
                default=ietf.group.models.default_groupman_roles, max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="groupfeatures",
            name="material_types",
            field=ietf.utils.db.EmptyAwareJSONField(
                default=ietf.group.models.default_material_types, max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="groupfeatures",
            name="matman_roles",
            field=ietf.utils.db.EmptyAwareJSONField(
                default=ietf.group.models.default_matman_roles, max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="groupfeatures",
            name="role_order",
            field=ietf.utils.db.EmptyAwareJSONField(
                default=ietf.group.models.default_role_order,
                help_text="The order in which roles are shown, for instance on photo pages.  Enter valid JSON.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="groupfeatures",
            name="session_purposes",
            field=ietf.utils.db.EmptyAwareJSONField(
                default=list,
                help_text="Allowed session purposes for this group type",
                max_length=256,
                validators=[
                    ietf.utils.validators.JSONForeignKeyListValidator(
                        ietf.name.models.SessionPurposeName
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="grouphistory",
            name="used_roles",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Leave an empty list to get the group_type's default used roles",
                max_length=256,
            ),
        ),
    ]
