# Copyright The IETF Trust 2019-2020, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-19 10:08


from django.db import migrations, models
import django.db.models.deletion
import ietf.utils.models

class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_new_group_features_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupfeatures',
            name='type',
            field=ietf.utils.models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='features', serialize=False, to='name.GroupTypeName'),
        ),
        migrations.AlterField(
            model_name='historicalgroupfeatures',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='name.GroupTypeName'),
        ),
    ]
