# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-07 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_auto_20190122_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupfeatures',
            name='has_dependencies',
        ),
        migrations.RemoveField(
            model_name='historicalgroupfeatures',
            name='has_dependencies',
        ),
    ]
