# Copyright The IETF Trust 2019-2020, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 13:02


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_add_group_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupfeatures',
            name='has_dependencies',
        ),
        migrations.RemoveField(
            model_name='historicalgroupfeatures',
            name='has_dependencies',
        ),
    ]
