# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-04 13:10
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0023_use_milestone_dates_default_to_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupfeatures',
            name='groupman_authroles',
            field=jsonfield.fields.JSONField(default=['Secretariat'], max_length=128),
        ),
        migrations.AddField(
            model_name='historicalgroupfeatures',
            name='groupman_authroles',
            field=jsonfield.fields.JSONField(default=['Secretariat'], max_length=128),
        ),
    ]
