# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-01 12:54
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    GroupFeatures = apps.get_model('group', 'GroupFeatures')
    program = GroupFeatures.objects.get(type_id='program')
    program.has_meetings = True
    program.matman_roles = ['lead', 'chair', 'secr']
    program.docman_roles = ['lead', 'chair', 'secr']
    program.groupman_roles = ['lead', 'chair', 'secr']
    program.role_order = ['lead', 'chair', 'secr']
    program.save()

def reverse(apps, schema_editor):
    GroupFeatures = apps.get_model('group', 'GroupFeatures')
    program = GroupFeatures.objects.get(type_id='program')
    program.has_meetings = False
    program.matman_roles = ['lead', 'secr']
    program.docman_roles = ['lead', 'secr']
    program.groupman_roles = ['lead', 'secr']
    program.role_order = ['lead', 'secr']
    program.save()

class Migration(migrations.Migration):

    dependencies = [
        ('group', '0025_populate_groupman_authroles'),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
