# Generated by Django 2.0.13 on 2020-05-22 12:00

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0028_add_robots'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='used_roles',
            field=jsonfield.fields.JSONField(default=[], help_text="Leave an empty list to get the group_type's default used roles", max_length=128),
        ),
        migrations.AddField(
            model_name='groupfeatures',
            name='default_used_roles',
            field=jsonfield.fields.JSONField(default=[], max_length=128),
        ),
        migrations.AddField(
            model_name='grouphistory',
            name='used_roles',
            field=jsonfield.fields.JSONField(default=[], help_text="Leave an empty list to get the group_type's default used roles", max_length=128),
        ),
        migrations.AddField(
            model_name='historicalgroupfeatures',
            name='default_used_roles',
            field=jsonfield.fields.JSONField(default=[], max_length=128),
        ),
    ]
