# Generated by Django 2.0.13 on 2020-06-15 11:10

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0030_populate_default_used_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='used_roles',
            field=jsonfield.fields.JSONField(blank=True, default=[], help_text="Leave an empty list to get the group_type's default used roles", max_length=128),
        ),
        migrations.AlterField(
            model_name='grouphistory',
            name='used_roles',
            field=jsonfield.fields.JSONField(blank=True, default=[], help_text="Leave an empty list to get the group_type's default used roles", max_length=128),
        ),
    ]
