# Generated by Django 2.2.17 on 2020-11-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0037_initial_yc_roles'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='groupevent',
            index=models.Index(fields=['-time', '-id'], name='group_group_time_ee7c7c_idx'),
        ),
    ]
