# Generated by Django 2.2.17 on 2020-12-11 08:48

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0039_remove_historicalgroupfeatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='used_roles',
            field=jsonfield.fields.JSONField(blank=True, default=[], help_text="Leave an empty list to get the group_type's default used roles", max_length=256),
        ),
        migrations.AlterField(
            model_name='groupfeatures',
            name='default_used_roles',
            field=jsonfield.fields.JSONField(default=[], max_length=256),
        ),
        migrations.AlterField(
            model_name='grouphistory',
            name='used_roles',
            field=jsonfield.fields.JSONField(blank=True, default=[], help_text="Leave an empty list to get the group_type's default used roles", max_length=256),
        ),
        # historicalgroupfeatures has been removed
        # migrations.AlterField(
        #     model_name='historicalgroupfeatures',
        #     name='default_used_roles',
        #     field=jsonfield.fields.JSONField(default=[], max_length=256),
        # ),
    ]
