# Copyright The IETF Trust 2022, All Rights Reserved
# Generated by Django 2.2.28 on 2022-07-14 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0056_dir_chair_groupman_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupfeatures',
            old_name='has_default_jabber',
            new_name='has_default_chat',
        ),
    ]
