export default [
  { label: 'Pacific - Niue', value: 'Pacific/Niue' },
  { label: 'Pacific - Pago Pago', value: 'Pacific/Pago_Pago' },
  { label: 'Pacific - Hawaii Time', value: 'Pacific/Honolulu' },
  { label: 'Pacific - Rarotonga', value: 'Pacific/Rarotonga' },
  { label: 'Pacific - Tahiti', value: 'Pacific/Tahiti' },
  { label: 'Pacific - Marquesas', value: 'Pacific/Marquesas' },
  { label: 'America - Alaska Time', value: 'America/Anchorage' },
  { label: 'Pacific - Gambier', value: 'Pacific/Gambier' },
  { label: 'America - Pacific Time - Los Angeles', value: 'America/Los_Angeles' },
  { label: 'America - Pacific Time - Tijuana', value: 'America/Tijuana' },
  { label: 'America - Pacific Time - Vancouver', value: 'America/Vancouver' },
  { label: 'America - Pacific Time - Whitehorse', value: 'America/Whitehorse' },
  { label: 'Pacific - Pitcairn', value: 'Pacific/Pitcairn' },
  { label: 'America - Mountain Time - Arizona', value: 'America/Phoenix' },
  { label: 'America - Mountain Time - Chihuahua, Mazatlan', value: 'America/Mazatlan' },
  { label: 'America - Mountain Time - Dawson Creek', value: 'America/Dawson_Creek' },
  { label: 'America - Mountain Time - Denver', value: 'America/Denver' },
  { label: 'America - Mountain Time - Edmonton', value: 'America/Edmonton' },
  { label: 'America - Mountain Time - Hermosillo', value: 'America/Hermosillo' },
  { label: 'America - Mountain Time - Yellowknife', value: 'America/Yellowknife' },
  { label: 'America - Belize', value: 'America/Belize' },
  { label: 'America - Central Time - Chicago', value: 'America/Chicago' },
  { label: 'America - Central Time - Mexico City', value: 'America/Mexico_City' },
  { label: 'America - Central Time - Regina', value: 'America/Regina' },
  { label: 'America - Central Time - Tegucigalpa', value: 'America/Tegucigalpa' },
  { label: 'America - Central Time - Winnipeg', value: 'America/Winnipeg' },
  { label: 'America - Costa Rica', value: 'America/Costa_Rica' },
  { label: 'America - El Salvador', value: 'America/El_Salvador' },
  { label: 'Pacific - Galapagos', value: 'Pacific/Galapagos' },
  { label: 'America - Guatemala', value: 'America/Guatemala' },
  { label: 'America - Managua', value: 'America/Managua' },
  { label: 'America - America Cancun', value: 'America/Cancun' },
  { label: 'America - Bogota', value: 'America/Bogota' },
  { label: 'Pacific - Easter Island', value: 'Pacific/Easter' },
  { label: 'America - Eastern Time - New York', value: 'America/New_York' },
  { label: 'America - Eastern Time - Iqaluit', value: 'America/Iqaluit' },
  { label: 'America - Eastern Time - Toronto', value: 'America/Toronto' },
  { label: 'America - Guayaquil', value: 'America/Guayaquil' },
  { label: 'America - Havana', value: 'America/Havana' },
  { label: 'America - Jamaica', value: 'America/Jamaica' },
  { label: 'America - Lima', value: 'America/Lima' },
  { label: 'America - Nassau', value: 'America/Nassau' },
  { label: 'America - Panama', value: 'America/Panama' },
  { label: 'America - Port-au-Prince', value: 'America/Port-au-Prince' },
  { label: 'America - Rio Branco', value: 'America/Rio_Branco' },
  { label: 'America - Atlantic Time - Halifax', value: 'America/Halifax' },
  { label: 'America - Barbados', value: 'America/Barbados' },
  { label: 'Atlantic - Bermuda', value: 'Atlantic/Bermuda' },
  { label: 'America - Boa Vista', value: 'America/Boa_Vista' },
  { label: 'America - Caracas', value: 'America/Caracas' },
  { label: 'America - Curacao', value: 'America/Curacao' },
  { label: 'America - Grand Turk', value: 'America/Grand_Turk' },
  { label: 'America - Guyana', value: 'America/Guyana' },
  { label: 'America - La Paz', value: 'America/La_Paz' },
  { label: 'America - Manaus', value: 'America/Manaus' },
  { label: 'America - Martinique', value: 'America/Martinique' },
  { label: 'America - Port of Spain', value: 'America/Port_of_Spain' },
  { label: 'America - Porto Velho', value: 'America/Porto_Velho' },
  { label: 'America - Puerto Rico', value: 'America/Puerto_Rico' },
  { label: 'America - Santo Domingo', value: 'America/Santo_Domingo' },
  { label: 'America - Thule', value: 'America/Thule' },
  { label: 'America - Newfoundland Time - St. Johns', value: 'America/St_Johns' },
  { label: 'America - Araguaina', value: 'America/Araguaina' },
  { label: 'America - Asuncion', value: 'America/Asuncion' },
  { label: 'America - Belem', value: 'America/Belem' },
  { label: 'America - Buenos Aires', value: 'America/Argentina/Buenos_Aires' },
  { label: 'America - Campo Grande', value: 'America/Campo_Grande' },
  { label: 'America - Cayenne', value: 'America/Cayenne' },
  { label: 'America - Cuiaba', value: 'America/Cuiaba' },
  { label: 'America - Fortaleza', value: 'America/Fortaleza' },
  { label: 'America - Godthab', value: 'America/Godthab' },
  { label: 'America - Maceio', value: 'America/Maceio' },
  { label: 'America - Miquelon', value: 'America/Miquelon' },
  { label: 'America - Montevideo', value: 'America/Montevideo' },
  { label: 'Antarctica - Palmer', value: 'Antarctica/Palmer' },
  { label: 'America - Paramaribo', value: 'America/Paramaribo' },
  { label: 'America - Punta Arenas', value: 'America/Punta_Arenas' },
  { label: 'America - Recife', value: 'America/Recife' },
  { label: 'Antarctica - Rothera', value: 'Antarctica/Rothera' },
  { label: 'America - Salvador', value: 'America/Bahia' },
  { label: 'America - Santiago', value: 'America/Santiago' },
  { label: 'Atlantic - Stanley', value: 'Atlantic/Stanley' },
  { label: 'America - Noronha', value: 'America/Noronha' },
  { label: 'America - Sao Paulo', value: 'America/Sao_Paulo' },
  { label: 'Atlantic - South Georgia', value: 'Atlantic/South_Georgia' },
  { label: 'Atlantic - Azores', value: 'Atlantic/Azores' },
  { label: 'Atlantic - Cape Verde', value: 'Atlantic/Cape_Verde' },
  { label: 'America - Scoresbysund', value: 'America/Scoresbysund' },
  { label: 'Africa - Abidjan', value: 'Africa/Abidjan' },
  { label: 'Africa - Accra', value: 'Africa/Accra' },
  { label: 'Africa - Bissau', value: 'Africa/Bissau' },
  { label: 'Atlantic - Canary Islands', value: 'Atlantic/Canary' },
  { label: 'Africa - Casablanca', value: 'Africa/Casablanca' },
  { label: 'America - Danmarkshavn', value: 'America/Danmarkshavn' },
  { label: 'Europe - Dublin', value: 'Europe/Dublin' },
  { label: 'Africa - El Aaiun', value: 'Africa/El_Aaiun' },
  { label: 'Atlantic - Faeroe', value: 'Atlantic/Faroe' },
  { label: 'UTC / GMT', value: 'UTC' },
  { label: 'Europe - Lisbon', value: 'Europe/Lisbon' },
  { label: 'Europe - London', value: 'Europe/London' },
  { label: 'Africa - Monrovia', value: 'Africa/Monrovia' },
  { label: 'Atlantic - Reykjavik', value: 'Atlantic/Reykjavik' },
  { label: 'Africa - Algiers', value: 'Africa/Algiers' },
  { label: 'Europe - Amsterdam', value: 'Europe/Amsterdam' },
  { label: 'Europe - Andorra', value: 'Europe/Andorra' },
  { label: 'Europe - Berlin', value: 'Europe/Berlin' },
  { label: 'Europe - Brussels', value: 'Europe/Brussels' },
  { label: 'Europe - Budapest', value: 'Europe/Budapest' },
  { label: 'Europe - Central European Time - Belgrade', value: 'Europe/Belgrade' },
  { label: 'Europe - Central European Time - Prague', value: 'Europe/Prague' },
  { label: 'Africa - Ceuta', value: 'Africa/Ceuta' },
  { label: 'Europe - Copenhagen', value: 'Europe/Copenhagen' },
  { label: 'Europe - Gibraltar', value: 'Europe/Gibraltar' },
  { label: 'Africa - Lagos', value: 'Africa/Lagos' },
  { label: 'Europe - Luxembourg', value: 'Europe/Luxembourg' },
  { label: 'Europe - Madrid', value: 'Europe/Madrid' },
  { label: 'Europe - Malta', value: 'Europe/Malta' },
  { label: 'Europe - Monaco', value: 'Europe/Monaco' },
  { label: 'Africa - Ndjamena', value: 'Africa/Ndjamena' },
  { label: 'Europe - Oslo', value: 'Europe/Oslo' },
  { label: 'Europe - Paris', value: 'Europe/Paris' },
  { label: 'Europe - Rome', value: 'Europe/Rome' },
  { label: 'Europe - Stockholm', value: 'Europe/Stockholm' },
  { label: 'Europe - Tirane', value: 'Europe/Tirane' },
  { label: 'Africa - Tunis', value: 'Africa/Tunis' },
  { label: 'Europe - Vienna', value: 'Europe/Vienna' },
  { label: 'Europe - Warsaw', value: 'Europe/Warsaw' },
  { label: 'Europe - Zurich', value: 'Europe/Zurich' },
  { label: 'Asia - Amman', value: 'Asia/Amman' },
  { label: 'Europe - Athens', value: 'Europe/Athens' },
  { label: 'Asia - Beirut', value: 'Asia/Beirut' },
  { label: 'Europe - Bucharest', value: 'Europe/Bucharest' },
  { label: 'Africa - Cairo', value: 'Africa/Cairo' },
  { label: 'Europe - Chisinau', value: 'Europe/Chisinau' },
  { label: 'Asia - Damascus', value: 'Asia/Damascus' },
  { label: 'Asia - Gaza', value: 'Asia/Gaza' },
  { label: 'Europe - Helsinki', value: 'Europe/Helsinki' },
  { label: 'Asia - Jerusalem', value: 'Asia/Jerusalem' },
  { label: 'Africa - Johannesburg', value: 'Africa/Johannesburg' },
  { label: 'Africa - Khartoum', value: 'Africa/Khartoum' },
  { label: 'Europe - Kiev', value: 'Europe/Kiev' },
  { label: 'Africa - Maputo', value: 'Africa/Maputo' },
  { label: 'Europe - Moscow-01 - Kaliningrad', value: 'Europe/Kaliningrad' },
  { label: 'Asia - Nicosia', value: 'Asia/Nicosia' },
  { label: 'Europe - Riga', value: 'Europe/Riga' },
  { label: 'Europe - Sofia', value: 'Europe/Sofia' },
  { label: 'Europe - Tallinn', value: 'Europe/Tallinn' },
  { label: 'Africa - Tripoli', value: 'Africa/Tripoli' },
  { label: 'Europe - Vilnius', value: 'Europe/Vilnius' },
  { label: 'Africa - Windhoek', value: 'Africa/Windhoek' },
  { label: 'Asia - Baghdad', value: 'Asia/Baghdad' },
  { label: 'Europe - Istanbul', value: 'Europe/Istanbul' },
  { label: 'Europe - Minsk', value: 'Europe/Minsk' },
  { label: 'Europe - Moscow+00 - Moscow', value: 'Europe/Moscow' },
  { label: 'Africa - Nairobi', value: 'Africa/Nairobi' },
  { label: 'Asia - Qatar', value: 'Asia/Qatar' },
  { label: 'Asia - Riyadh', value: 'Asia/Riyadh' },
  { label: 'Antarctica - Syowa', value: 'Antarctica/Syowa' },
  { label: 'Asia - Tehran', value: 'Asia/Tehran' },
  { label: 'Asia - Baku', value: 'Asia/Baku' },
  { label: 'Asia - Dubai', value: 'Asia/Dubai' },
  { label: 'Indian - Mahe', value: 'Indian/Mahe' },
  { label: 'Indian - Mauritius', value: 'Indian/Mauritius' },
  { label: 'Europe - Moscow+01 - Samara', value: 'Europe/Samara' },
  { label: 'Indian - Reunion', value: 'Indian/Reunion' },
  { label: 'Asia - Tbilisi', value: 'Asia/Tbilisi' },
  { label: 'Asia - Yerevan', value: 'Asia/Yerevan' },
  { label: 'Asia - Kabul', value: 'Asia/Kabul' },
  { label: 'Asia - Aqtau', value: 'Asia/Aqtau' },
  { label: 'Asia - Aqtobe', value: 'Asia/Aqtobe' },
  { label: 'Asia - Ashgabat', value: 'Asia/Ashgabat' },
  { label: 'Asia - Dushanbe', value: 'Asia/Dushanbe' },
  { label: 'Asia - Karachi', value: 'Asia/Karachi' },
  { label: 'Indian - Kerguelen', value: 'Indian/Kerguelen' },
  { label: 'Indian - Maldives', value: 'Indian/Maldives' },
  { label: 'Antarctica - Mawson', value: 'Antarctica/Mawson' },
  { label: 'Asia - Moscow+02 - Yekaterinburg', value: 'Asia/Yekaterinburg' },
  { label: 'Asia - Tashkent', value: 'Asia/Tashkent' },
  { label: 'Asia - Colombo', value: 'Asia/Colombo' },
  { label: 'Asia - India Standard Time', value: 'Asia/Kolkata' },
  { label: 'Asia - Kathmandu', value: 'Asia/Kathmandu' },
  { label: 'Asia - Almaty', value: 'Asia/Almaty' },
  { label: 'Asia - Bishkek', value: 'Asia/Bishkek' },
  { label: 'Indian - Chagos', value: 'Indian/Chagos' },
  { label: 'Asia - Dhaka', value: 'Asia/Dhaka' },
  { label: 'Asia - Moscow+03 - Omsk', value: 'Asia/Omsk' },
  { label: 'Asia - Thimphu', value: 'Asia/Thimphu' },
  { label: 'Antarctica - Vostok', value: 'Antarctica/Vostok' },
  { label: 'Indian - Cocos', value: 'Indian/Cocos' },
  { label: 'Asia - Rangoon', value: 'Asia/Yangon' },
  { label: 'Asia - Bangkok', value: 'Asia/Bangkok' },
  { label: 'Indian - Christmas', value: 'Indian/Christmas' },
  { label: 'Antarctica - Davis', value: 'Antarctica/Davis' },
  { label: 'Asia - Hanoi', value: 'Asia/Saigon' },
  { label: 'Asia - Hovd', value: 'Asia/Hovd' },
  { label: 'Asia - Jakarta', value: 'Asia/Jakarta' },
  { label: 'Asia - Moscow+04 - Krasnoyarsk', value: 'Asia/Krasnoyarsk' },
  { label: 'Asia - Brunei', value: 'Asia/Brunei' },
  { label: 'Asia - China Time - Beijing', value: 'Asia/Shanghai' },
  { label: 'Asia - Choibalsan', value: 'Asia/Choibalsan' },
  { label: 'Asia - Hong Kong', value: 'Asia/Hong_Kong' },
  { label: 'Asia - Kuala Lumpur', value: 'Asia/Kuala_Lumpur' },
  { label: 'Asia - Macau', value: 'Asia/Macau' },
  { label: 'Asia - Makassar', value: 'Asia/Makassar' },
  { label: 'Asia - Manila', value: 'Asia/Manila' },
  { label: 'Asia - Moscow+05 - Irkutsk', value: 'Asia/Irkutsk' },
  { label: 'Asia - Singapore', value: 'Asia/Singapore' },
  { label: 'Asia - Taipei', value: 'Asia/Taipei' },
  { label: 'Asia - Ulaanbaatar', value: 'Asia/Ulaanbaatar' },
  { label: 'Australia - Western Time - Perth', value: 'Australia/Perth' },
  { label: 'Asia - Pyongyang', value: 'Asia/Pyongyang' },
  { label: 'Asia - Dili', value: 'Asia/Dili' },
  { label: 'Asia - Jayapura', value: 'Asia/Jayapura' },
  { label: 'Asia - Moscow+06 - Yakutsk', value: 'Asia/Yakutsk' },
  { label: 'Pacific - Palau', value: 'Pacific/Palau' },
  { label: 'Asia - Seoul', value: 'Asia/Seoul' },
  { label: 'Asia - Tokyo', value: 'Asia/Tokyo' },
  { label: 'Australia - Central Time - Darwin', value: 'Australia/Darwin' },
  { label: 'Antarctica - Dumont D\'Urville', value: 'Antarctica/DumontDUrville' },
  { label: 'Australia - Eastern Time - Brisbane', value: 'Australia/Brisbane' },
  { label: 'Pacific - Guam', value: 'Pacific/Guam' },
  { label: 'Asia - Moscow+07 - Vladivostok', value: 'Asia/Vladivostok' },
  { label: 'Pacific - Port Moresby', value: 'Pacific/Port_Moresby' },
  { label: 'Pacific - Truk', value: 'Pacific/Chuuk' },
  { label: 'Australia - Central Time - Adelaide', value: 'Australia/Adelaide' },
  { label: 'Antarctica - Casey', value: 'Antarctica/Casey' },
  { label: 'Australia - Eastern Time - Hobart', value: 'Australia/Hobart' },
  { label: 'Australia - Eastern Time - Melbourne, Sydney', value: 'Australia/Sydney' },
  { label: 'Pacific - Efate', value: 'Pacific/Efate' },
  { label: 'Pacific - Guadalcanal', value: 'Pacific/Guadalcanal' },
  { label: 'Pacific - Kosrae', value: 'Pacific/Kosrae' },
  { label: 'Asia - Moscow+08 - Magadan', value: 'Asia/Magadan' },
  { label: 'Pacific - Norfolk', value: 'Pacific/Norfolk' },
  { label: 'Pacific - Noumea', value: 'Pacific/Noumea' },
  { label: 'Pacific - Ponape', value: 'Pacific/Pohnpei' },
  { label: 'Pacific - Funafuti', value: 'Pacific/Funafuti' },
  { label: 'Pacific - Kwajalein', value: 'Pacific/Kwajalein' },
  { label: 'Pacific - Majuro', value: 'Pacific/Majuro' },
  { label: 'Asia - Moscow+09 - Petropavlovsk-Kamchatskiy', value: 'Asia/Kamchatka' },
  { label: 'Pacific - Nauru', value: 'Pacific/Nauru' },
  { label: 'Pacific - Tarawa', value: 'Pacific/Tarawa' },
  { label: 'Pacific - Wake', value: 'Pacific/Wake' },
  { label: 'Pacific - Wallis', value: 'Pacific/Wallis' },
  { label: 'Pacific - Auckland', value: 'Pacific/Auckland' },
  { label: 'Pacific - Enderbury', value: 'Pacific/Enderbury' },
  { label: 'Pacific - Fakaofo', value: 'Pacific/Fakaofo' },
  { label: 'Pacific - Fiji', value: 'Pacific/Fiji' },
  { label: 'Pacific - Tongatapu', value: 'Pacific/Tongatapu' },
  { label: 'Pacific - Apia', value: 'Pacific/Apia' },
  { label: 'Pacific - Kiritimati', value: 'Pacific/Kiritimati' }
]
