# Copyright The IETF Trust 2019-2020, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 03:06


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_copy_docs_m2m_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitylistdocs',
            name='communitylist',
        ),
        migrations.RemoveField(
            model_name='communitylistdocs',
            name='document',
        ),
        migrations.RemoveField(
            model_name='searchruledocs',
            name='document',
        ),
        migrations.RemoveField(
            model_name='searchruledocs',
            name='searchrule',
        ),
        migrations.RemoveField(
            model_name='communitylist',
            name='added_docs2',
        ),
        migrations.RemoveField(
            model_name='searchrule',
            name='name_contains_index2',
        ),
        migrations.DeleteModel(
            name='CommunityListDocs',
        ),
        migrations.DeleteModel(
            name='SearchRuleDocs',
        ),
    ]
