# Copyright The IETF Trust 2019-2020, All Rights Reserved
# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-15 20:59


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0019_auto_20191023_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsecretarysettings',
            name='days_to_show_in_reviewer_list',
            field=models.IntegerField(blank=True, help_text='Maximum number of days to show in reviewer list for completed items.', null=True),
        ),
        migrations.AddField(
            model_name='reviewsecretarysettings',
            name='max_items_to_show_in_reviewer_list',
            field=models.IntegerField(blank=True, help_text='Maximum number of completed items to show for one reviewer in the reviewer list view, the list is also filtered by the days to show in reviews list setting.', null=True),
        ),
    ]
