# Generated by Django 4.2.11 on 2024-05-03 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VersionInfo",
        ),
    ]
