# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_dumpinfo_tz'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('command', models.CharField(max_length=32)),
                ('switch', models.CharField(max_length=16)),
                ('version', models.CharField(max_length=64)),
                ('used', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'VersionInfo',
            },
        ),
    ]
