# Generated by Django 2.2.28 on 2022-11-10 09:27

from django.conf import settings
from django.db import migrations

def forward(apps, schema_editor):
    assert(settings.DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql_psycopg2', 'Please change to use postgres before continuing')

def reverse(apps, schema_editor):
    assert(settings.DATABASES['default']['ENGINE'] == 'django.db.backends.mysql', 'Please change to use mariadb before continuing')

class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_pause_to_change_use_tz'),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
