# Generated by Django 4.2.7 on 2023-11-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperson",
            name="biography",
            field=models.TextField(
                blank=True,
                help_text="Short biography for use on leadership pages. Use plain text or Markdown.",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="biography",
            field=models.TextField(
                blank=True,
                help_text="Short biography for use on leadership pages. Use plain text or Markdown.",
            ),
        ),
    ]
