# Generated by Django 4.2.13 on 2024-05-22 18:50

from django.db import migrations, models
import ietf.person.models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperson",
            name="ascii",
            field=models.CharField(
                help_text="Name as rendered in ASCII (Latin, unaccented) characters.",
                max_length=255,
                validators=[ietf.person.models.name_character_validator],
                verbose_name="Full Name (ASCII)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalperson",
            name="ascii_short",
            field=models.CharField(
                blank=True,
                help_text="Example: A. Nonymous.  Fill in this with initials and surname only if taking the initials and surname of the ASCII name above produces an incorrect initials-only form. (Blank is OK).",
                max_length=32,
                null=True,
                validators=[ietf.person.models.name_character_validator],
                verbose_name="Abbreviated Name (ASCII)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalperson",
            name="plain",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Use this if you have a Spanish double surname.  Don't use this for nicknames, and don't use it unless you've actually observed that the datatracker shows your name incorrectly.",
                max_length=64,
                validators=[ietf.person.models.name_character_validator],
                verbose_name="Plain Name correction (Unicode)",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="ascii",
            field=models.CharField(
                help_text="Name as rendered in ASCII (Latin, unaccented) characters.",
                max_length=255,
                validators=[ietf.person.models.name_character_validator],
                verbose_name="Full Name (ASCII)",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="ascii_short",
            field=models.CharField(
                blank=True,
                help_text="Example: A. Nonymous.  Fill in this with initials and surname only if taking the initials and surname of the ASCII name above produces an incorrect initials-only form. (Blank is OK).",
                max_length=32,
                null=True,
                validators=[ietf.person.models.name_character_validator],
                verbose_name="Abbreviated Name (ASCII)",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="plain",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Use this if you have a Spanish double surname.  Don't use this for nicknames, and don't use it unless you've actually observed that the datatracker shows your name incorrectly.",
                max_length=64,
                validators=[ietf.person.models.name_character_validator],
                verbose_name="Plain Name correction (Unicode)",
            ),
        ),
    ]
