# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20180330_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.RemoveField(
            model_name='personhistory',
            name='address',
        ),
    ]
