# Generated by Django 4.2.30 on 2026-07-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0005_alter_historicalperson_pronouns_selectable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalapikey",
            name="endpoint",
            field=models.CharField(
                choices=[
                    ("/api/iesg/position", "/api/iesg/position"),
                    (
                        "/api/meeting/session/recording-name",
                        "/api/meeting/session/recording-name",
                    ),
                    (
                        "/api/meeting/session/video/url",
                        "/api/meeting/session/video/url",
                    ),
                    ("/api/notify/meeting/bluesheet", "/api/notify/meeting/bluesheet"),
                    (
                        "/api/notify/meeting/registration",
                        "/api/notify/meeting/registration",
                    ),
                    ("/api/notify/session/attendees", "/api/notify/session/attendees"),
                    ("/api/notify/session/chatlog", "/api/notify/session/chatlog"),
                    ("/api/notify/session/polls", "/api/notify/session/polls"),
                    ("/api/v2/person/person", "/api/v2/person/person"),
                ],
                max_length=128,
            ),
        ),
    ]
