# Generated by Django 4.2.30 on 2026-09-09 17:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0006_personuuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issuer", models.CharField(max_length=255)),
                ("sub", models.CharField(blank=True, max_length=255, null=True)),
                ("ak_uuid", models.UUIDField()),
                ("ak_pk", models.IntegerField(blank=True, null=True)),
                ("username", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[("active", "Active"), ("superseded", "Superseded")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "linked_by",
                    models.CharField(
                        choices=[
                            ("password", "Password"),
                            ("email", "Email"),
                            ("operator", "Operator"),
                            ("new_account", "New Account"),
                        ],
                        max_length=16,
                    ),
                ),
                ("ak_active", models.BooleanField(default=True)),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to="person.person",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "external identities",
            },
        ),
        migrations.AddConstraint(
            model_name="externalidentity",
            constraint=models.UniqueConstraint(
                fields=("issuer", "sub"), name="unique_external_sub_per_issuer"
            ),
        ),
        migrations.AddConstraint(
            model_name="externalidentity",
            constraint=models.UniqueConstraint(
                fields=("issuer", "ak_uuid"), name="unique_external_uuid_per_issuer"
            ),
        ),
        migrations.AddConstraint(
            model_name="externalidentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "active")),
                fields=("person",),
                name="unique_active_external_identity_per_person",
            ),
        ),
    ]
