# Generated by Django 2.0.13 on 2020-06-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_auto_20200415_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalapikey',
            name='endpoint',
            field=models.CharField(choices=[('/api/iesg/position', '/api/iesg/position'), ('/api/v2/person/person', '/api/v2/person/person'), ('/api/meeting/session/video/url', '/api/meeting/session/video/url'), ('/api/person/access/meetecho', '/api/person/access/meetecho'), ('/api/notify/meeting/registration', '/api/notify/meeting/registration')], max_length=128),
        ),
    ]
