# Generated by Django 2.1.15 on 2020-06-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_auto_20200608_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperson',
            name='consent',
            field=models.BooleanField(default=None, null=True, verbose_name='I hereby give my consent to the use of the personal details I have provided (photo, bio, name, email) within the IETF Datatracker'),
        ),
        migrations.AlterField(
            model_name='person',
            name='consent',
            field=models.BooleanField(default=None, null=True, verbose_name='I hereby give my consent to the use of the personal details I have provided (photo, bio, name, email) within the IETF Datatracker'),
        ),
    ]
