# Generated by Django 2.2.15 on 2020-08-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0015_extres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalapikey',
            name='endpoint',
            field=models.CharField(choices=[('/api/iesg/position', '/api/iesg/position'), ('/api/v2/person/person', '/api/v2/person/person'), ('/api/meeting/session/video/url', '/api/meeting/session/video/url'), ('/api/notify/meeting/registration', '/api/notify/meeting/registration'), ('/api/notify/meeting/bluesheet', '/api/notify/meeting/bluesheet')], max_length=128),
        ),
    ]
