# Generated by Django 2.2.17 on 2020-11-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0017_auto_20201028_0902'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='personevent',
            index=models.Index(fields=['-time', '-id'], name='person_pers_time_8dfbc5_idx'),
        ),
    ]
