# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-01 03:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0019_add_discovered_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='address',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
