# Generated by Django 2.2.28 on 2022-06-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0022_auto_20220513_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='pronouns',
            field=models.CharField(blank=True, help_text='Optionally provide your personal pronouns. These will be displayed on your public profile page and alongside your name in Meetecho and, in future, other systems.', max_length=20, null=True, verbose_name='Pronouns'),
        ),
        migrations.AddField(
            model_name='person',
            name='pronouns',
            field=models.CharField(blank=True, help_text='Optionally provide your personal pronouns. These will be displayed on your public profile page and alongside your name in Meetecho and, in future, other systems.', max_length=20, null=True, verbose_name='Pronouns'),
        ),
    ]
