# Generated by Django 2.2.28 on 2022-10-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0025_chat_and_polls_apikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalperson',
            name='consent',
        ),
        migrations.RemoveField(
            model_name='person',
            name='consent',
        ),
    ]
