# Generated by Django 2.2.28 on 2023-02-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0029_use_timezone_now_for_person_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='origin',
            field=models.CharField(help_text="The origin of the address: the user's email address, or 'author: DRAFTNAME' if an Internet-Draft, or 'role: GROUP/ROLE' if a role.", max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalemail',
            name='origin',
            field=models.CharField(help_text="The origin of the address: the user's email address, or 'author: DRAFTNAME' if an Internet-Draft, or 'role: GROUP/ROLE' if a role.", max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='name_from_draft',
            field=models.CharField(editable=False, help_text='Name as found in an Internet-Draft submission.', max_length=255, null=True, verbose_name='Full Name (from submission)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_from_draft',
            field=models.CharField(editable=False, help_text='Name as found in an Internet-Draft submission.', max_length=255, null=True, verbose_name='Full Name (from submission)'),
        ),
    ]
