# Generated by Django 2.2.28 on 2023-01-26 19:45

import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0030_id_term'),
        ('utils', '0004_pause_to_change_database_engines'),
    ]

    operations = [
        CITextExtension(),
        migrations.AlterField(
            model_name='email',
            name='address',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='historicalemail',
            name='address',
            field=django.contrib.postgres.fields.citext.CICharField(db_index=True, max_length=64, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
