# Generated by Django 2.2.28 on 2023-02-10 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0030_id_term_1'),
        ('person', '0031_id_term_2'),
    ]

    operations = [
    ]
