name: Build Dev/Test Blobstore Docker Image

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/build-devblobstore.yml'

  workflow_dispatch: 

env:
  MINIO_VERSION: latest

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Build & Push
      uses: docker/build-push-action@v6
      env:
        DOCKER_BUILD_NO_SUMMARY: true
      with:
        context: .
        file: docker/devblobstore.Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        build-args: MINIO_VERSION=${{ env.MINIO_VERSION }}
        tags: |
          ghcr.io/ietf-tools/datatracker-devblobstore:${{ env.MINIO_VERSION }}
          ghcr.io/ietf-tools/datatracker-devblobstore:latest
