name: Build Celery Worker Docker Image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'requirements.txt'
      - 'dev/celery/**'
      - '.github/workflows/build-celery-worker.yml'

  workflow_dispatch: 

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Build & Push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: dev/celery/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/ietf-tools/datatracker-celery:latest

